sonata-project/SonataMediaBundle

.travis.yml, composer.json
- Made composer update itself before usage (fix travis CI errors on packages using the new "^")
- Removed redundant old AWS SDK v.1 and replaced it with the new v.2 that is actually used
- Fixed dependency on datagrid-bundle
=> Fix tests (composer version and update package dependencies)

Tests/Filesystem/LocalTest.php
Fixes an annoying test failure due to /tmp being a symlink to /private/tmp on Mac Os X systems.
=> Mac OS X specific filesystem test fix

Tests/Metadata/AmazonMetadataBuilderTest.php
Update test considering full migration to v2 of the AWS library.
Replaces #688
=> Update AmazonMetadataBuilderTest to AWS v.2

Provider/BaseProvider.php
Exception is thrown by Gaufrette Filesystem
https://github.com/KnpLabs/Gaufrette/blob/master/src/Gaufrette/Filesystem.php#L161
=> Fix Remove media files in preRemove instead of postRemove

Admin/BaseMediaAdmin.php, Controller/MediaAdminController.php
Check if key 'context' exists in filter to prevent "undefined index: context" error from appearing when deleting several media at a time in admin.
=> Prevent "undefined index: context" error for batch delete action

Resources/config/doctrine/BaseMedia.phpcr.xml
Hello,
To be able to use Youtube video, size must be nullable (because YT service does not return the size)
The modification seems to me done for ORM but not PHPCR
Regards,
Peekmo
=> [PHPCR] size nullable

Tests/Controller/Api/MediaControllerTest.php
Removed not callable MediaProviderInterface::transform from test
fix for #722 **Bug in testPutMediumBinaryContentAction**
=> Removed not callable MediaProviderInterface::transform from test

Resources/doc/reference/installation.rst
Without `SonataIntlBundle` the admin wouldn't work as its views use `number_format_decimal` Twig filter, redo #727
=> Specify SonataIntlBundle dependency

Command/SyncThumbsCommand.php
I encountered such problem - when trying to sync large amount of thumbnails (6000+) command gets aborted by memory limit, cause it fetches all medias at once in one batch. This PR introduces medias processing in batches (batch size can be changed via --batchSize option and equals to 100 by default). So now this command can process as many thumbnails, as we have.
=> Sync thumbnails command optimization

Form/Type/MediaType.php
The form type media_type can be manipulated with events, inherits etc 
Now we can remove element unlink without have 
Child "unlink" does not exist. - 500 Internal Server Error - OutOfBoundsException
=> Ensure element unlink exist

CHANGELOG.md, Command/RemoveThumbsCommand.php, Provider/BaseProvider.php, Provider/MediaProviderInterface.php, Resources/doc/reference/command_line.rst, Thumbnail/ConsumerThumbnail.php, Thumbnail/FormatThumbnail.php, Thumbnail/LiipImagineThumbnail.php, Thumbnail/ThumbnailInterface.php
With this command we can remove thumbnails of specified format or even all thumbnails.
This one will remove all thumbs of `small` format from `default` context:
```bash
app/console sonata:media:remove-thumbnails sonata.media.provider.image default small
```
This one will remove all thumbs from `default` context:
```bash
app/console sonata:media:remove-thumbnails sonata.media.provider.image default all
```
Also, command gives ability to choose provider, context and format, if any of them are not specifed in command line.
=> Implement remove-thumbnails command

Metadata/AmazonMetadataBuilder.php, Tests/Metadata/AmazonMetadataBuilderTest.php
S3Client does accept CacheControl as option instead of headers - Cache-Control.
before:
after:
=> fixed aws cache-control metadata

Provider/Pool.php, Tests/Provider/PoolTest.php
| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | yes
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| License       | MIT
Example:
```
Unable to retrieve the provider named "some_provider". Available providers are "provider_a", "provider_b", "provider_c"
```
Maybe the change of the exception type could be considered as a small BC break: previously it was ```RuntimeException``` and now it's changed for ```InvalidArgumentException``` (since it's more accurate for this case).
=> Improved exception message for invalid provider name

Tests/Provider/BaseProviderTest.php, composer.json
Basically, we have to lock sonata-admin 2.3 version because of BC break change in 2.4 (ErrorElement).
dev-master version of media-bundle should be used to works with sonata-admin 2.4.
=> Fix 2.3 tests

Tests/Provider/DailyMotionProviderTest.php, Tests/Provider/VimeoProviderTest.php, Tests/Provider/YouTubeProviderTest.php, composer.json
| Q             | A
| ------------- | ---
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | #819
| License       | MIT
| Doc PR        |
Replaced by ```Buzz\Message\AbstractMessage``` since ```Buzz\Message\MessageInterface```
is available from ```kriswallsmith/buzz: 0.6``` and the lowest resolved version
is 0.3.
Closes #819.
=> [2.3] Updated references to "Buzz\Message\MessageInterface" in tests

Resources/translations/SonataMediaBundle.en.xliff, Resources/translations/SonataMediaBundle.es.xliff, Resources/translations/SonataMediaBundle.fr.xliff, Resources/translations/SonataMediaBundle.it.xliff, Resources/translations/SonataMediaBundle.lt.xliff, Resources/translations/SonataMediaBundle.pl.xliff, Resources/translations/SonataMediaBundle.ro.xliff, Resources/translations/SonataMediaBundle.ru.xliff, Resources/translations/SonataMediaBundle.uk.xliff
Reverts sonata-project/SonataMediaBundle#844
This PR should be review deeper.
For sample, FR language need a space before `:`. Possibly the same for another.
@OskarStark Please fix only English and your language if you think it's a typo on a new PR.
=> Revert "streamlined sentence. removed whitespace."

Command/AddMediaCommand.php, Metadata/ProxyMetadataBuilder.php
This properties were never used.
=> Removed unused properties

Metadata/ProxyMetadataBuilder.php, Resources/config/gaufrette.xml
This property is never used and should be removed in the next major version.
=> Removed unused parameter

Tests/Provider/ImageProviderTest.php, Thumbnail/FormatThumbnail.php
This fixes a bug in [Sonata\MediaBundle\Thumbnail\FormatThumbnail::generatePrivateUrl()](https://github.com/sonata-project/SonataMediaBundle/blob/2.3/Thumbnail/FormatThumbnail.php#L46) that causes an incorrect file name to be returned when the "reference" format is requested. The bug impacts X-Sendfile and X-Accel-Redirect send modes. This is a follow-up to #232 and #277. Additional discussion can be found in #787.
=> [2.3][Thumbnail] Fix thumbnail URL for reference format

Provider/VimeoProvider.php, Tests/Provider/VimeoProviderTest.php
I've extended the Vimeo provider, because links like 'player.vimeo.com/video/123456' do not get properly parsed. With this regexp both 'vimeo.com/123456' and 'player.vimeo.com/123456' work
=> Extended regexp for Vimeo provider

Resources/config/consumer.xml, Thumbnail/ConsumerThumbnail.php
when using rabbitmq, there is a race condition because of the database transaction. In our case the worker was too fast and the database entry didn't exist at the time the consumer was processed.
Our solution was to use the event dispatcher and publish the job just at the end of the request (``kernel.finish_request``). This even works if used with sonata-notification-bundle strategy postpone which uses the kernel.terminate event.
=> publish job on kernel.finish_request

DependencyInjection/SonataMediaExtension.php, Metadata/AmazonMetadataBuilder.php, Resources/config/gaufrette.xml, Resources/doc/index.rst, Resources/doc/reference/amazon_s3.rst, composer.json
This came as a result of https://github.com/sonata-project/SonataMediaBundle/issues/895 and is my attempt at cherry picking the commits into 2.3 branch that introduced compatibility with aws/aws-sdk-php on the master branch, as it's been a year since the first one. "It works for me" but I'm not sure if I missed any commits related to this. @Bladrak @toooni @rande maybe you guys would know :)
=> AWS S3 sdk support for 2.3 branch

DependencyInjection/SonataMediaExtension.php, composer.json
As the REST bundle is not required for the this bundle, the api form and controllers definitions should only be loaded, when the bundles are used.
=> Make REST Bundle optional

Provider/MediaProviderInterface.php, Tests/Provider/BaseProviderTest.php, Tests/Twig/Extension/MediaExtensionTest.php, Twig/Extension/MediaExtension.php
Delegate the responsibility of populating the options to the provider object.
That way the provider can add new items to the options array, making the media extension
more extendable.
=> Refactor thumbnail Twig helper

Command/FixMediaContextCommand.php, Resources/doc/reference/command_line.rst, Tests/Command/FixMediaContextCommandTest.php
This command is based on https://github.com/sonata-project/SonataClassificationBundle/blob/master/Command/FixContextCommand.php to create default categories defined under ``sonata_media => contexts`` in the configuration.
=> Created new command for creating default categories

Model/Media.php, Tests/Entity/MediaTest.php
| Q             | A
| ------------- | ---
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets |
| License       | MIT
| Doc PR        |
Updated ```Media::getExtension()``` in order to strip off query strings and hashes
from remote filenames.
Before:
```php
$media->setProviderReference('https://sonata-project.org/bundles/sonatageneral/images/logo-small.png?some-query-string=1#with-some-hash');
$media->getExtension(); // returns "png?some-query-string=1#with-some-hash"
```
After:
```php
$media->setProviderReference('https://sonata-project.org/bundles/sonatageneral/images/logo-small.png?some-query-string=1#with-some-hash');
$media->getExtension(); // returns "png"
```
=> Updated Media::getExtension()

.travis.yml, CDN/CloudFront.php, DependencyInjection/Compiler/SecurityContextCompilerPass.php, Model/Media.php, Resources/config/security.xml, Security/RolesDownloadStrategy.php, SonataMediaBundle.php, Tests/CDN/CloudFrontTest.php, Tests/Security/RolesDownloadStrategyTest.php, Tests/Validator/FormatValidatorTest.php, Validator/FormatValidator.php, composer.json
This PR should fix the remaining Symfony 3 compatibility issues based on the test suite and fixes one bug.
- Changes Travis-CI to test on stable versions of 2.8 and 3.0
- Changes `Form::bind()` calls to `Form::submit()`
- Handles deprecation of the `SecurityContextInterface` and associated `security.context` service
- Handles deprecation of the pre-2.5 validator API
- Corrects a call to a non-existing method in the `FormatValidator`
=> Symfony 3 compatibility

Resources/doc/reference/advanced_configuration.rst, Resources/doc/reference/amazon_s3.rst, Resources/doc/reference/api.rst, Resources/doc/reference/creating_a_provider_class.rst, Resources/doc/reference/form.rst, Resources/doc/reference/installation.rst, Resources/doc/reference/troubleshooting.rst, Tests/Metadata/AmazonMetadataBuilderTest.php
- quote meta characters in YAML
- remove highlighting for http block
Http does not seem to be recognized at all. If it is, there is no color
in the output, so…
- use another syntax for twig snippet
Conflicts:
Resources/doc/reference/installation.rst
=> Make the documentation parseable by sphinx 1.3.5

Resources/config/validation.xml, Tests/Validator/FormatValidatorTest.php, composer.json
Hello guys.
Could you please, merge this pull request into 2.3 stable branch? It will be awesome if you will do that for us.
This PR help many people to resolve issue with wrong namespace in the validation.xml.
p.s. I tried to get around this problem and set my own validation.xml in the Application\Sonata\MediaBundle. I tried to add validation groups on this constraint but it didn't help.
=> Extract validator from AdminBundle

Resources/doc/reference/security.rst
Post-increment operator replaced by + 1 so the session variable increases every time the media is downloaded
=> Fix media access times increment in session variable

Controller/MediaAdminController.php, Resources/views/MediaAdmin/list.html.twig
| Question       | Answer
|----------------|-------------------------------------------------------------
| Bundle version | sonata-project/media-bundle              dev-master b676113 
| Symfony version| symfony/symfony                          v2.8.4
| php version    | PHP 7.0.4-7ubuntu2
Deleting media object from list view was not being successful although getting the success message. 
On Media list view press filter once and then try to delete and object. Object is not being deleted. If you press the filter again and again, then you can delete the object.
Changed the value of category in datagrid to category object. It was being set only category id. If the category id is set by request from tree list, then we find one object by id and context and set the datagrid category to this …
=> datagrid category value must be object, it was being set to integer

Provider/FileProvider.php, Tests/Provider/FileProviderTest.php
Hi,
This PR provide support for stream wrapped paths (including Gaufrette) as pre-processed binaryContent.
In `FileProvider#setFileContents()` (**L 310**), the "realpath" to the pre-processed file is determined using `$media->getBinaryContent()->getRealPath()`. However, this returns `false` for stream wrapped paths (at least Gaufrette does). This causes a `ContextErrorException: Warning: file_get_contents(): Filename cannot be empty` error in Symfony.
With this PR, we now rely on  `$media->getBinaryContent()->getPathName()` if (and only if) `getRealPath()` fails, allowing the use of stream wrapped files.
This allow us, for example, to use Gaufrette's InMemoryAdapter to store pre-processed files and stop dealing with temporary files.
Since there were no tests for `setFileContents()`, I …
=> Support binary content which have in memory path

DependencyInjection/SonataMediaExtension.php
Replaces #923
```markdown
- Added `region` key to S3Client config
```
pass the region for aws sdk to generate signature
https://github.com/aws/aws-sdk-php/blob/2.7.27/src/Aws/S3/S3Client.php#L272
> +1 - this is also required for S3Client doesBucketExist to work. If region is not provided in the client constructor, amazon returns a 302 redirect requesting you to use an URL including region, causing gaufrette to conclude that the bucket does not exist and try to create the bucket in AwsS3::ensureBucketExists. Since the bucket does exist, you end up getting a BucketAlreadyOwnedByYouException with the message "Your previous request to create the named bucket succeeded and you already own it.". Simply passing region to the constructor as above resolves this error.
=> add region to S3Client config

Resources/doc/reference/installation.rst
Replaces #957 
> composer require should not have the flag --no-update when only one package is required.
> 
> Would introduce some confusion
=> composer require should not have the flag --no-update

Provider/BaseProvider.php
```markdown
- Added missing `BaseProvider::$name` property
```
The property is used at several positions (e.g. `BaseProvider::setName` or `BaseProvider::getName`).
=> Added missing BaseProvider::$name property

Admin/GalleryAdmin.php
Rebase of #616
```markdown
- Removed double translation in gallery edit form
```
The form groups are translated in the twig template.
=> Removed double translation in gallery edit form

Listener/ORM/MediaEventSubscriber.php, Tests/Listener/ORM/MediaEventSubscriberTest.php
Closes sonata-project/SonataClassificationBundle#60
Replaces #780 
```markdown
- Added `Sonata\MediaBundle\Listener\ORM\MediaEventSubscriber::onClear` to clear the `rootCategories` cache when the EntityManager is cleared.
- `Sonata\MediaBundle\Listener\ORM\MediaEventSubscriber::onClear` now subscribes to `onClear` too.
- Reuse of root categories instances after the entity manager has been cleared.
```
The issue wasn't reported in MediaBundle because the error is reported on ClassificationBundle Entities. Please refer to sonata-project/SonataClassificationBundle#60 for more details
=> Ensure ClassificationBundle related entities (Categories & Cie) are refreshed after a ObjectManager#clear

Tests/Twig/Extension/MediaExtensionTest.php, Twig/Extension/MediaExtension.php
Replaces #682
```markdown
- Added `alt` attribute to thumbnail twig tag
```
=> added alt attribute to thumbnail

Block/GalleryBlockService.php, Resources/translations/SonataMediaBundle.bg.xliff, Resources/translations/SonataMediaBundle.de.xliff, Resources/translations/SonataMediaBundle.en.xliff, Resources/translations/SonataMediaBundle.es.xliff, Resources/translations/SonataMediaBundle.fa.xliff, Resources/translations/SonataMediaBundle.fi.xliff, Resources/translations/SonataMediaBundle.fr.xliff, Resources/translations/SonataMediaBundle.hu.xliff, Resources/translations/SonataMediaBundle.it.xliff, Resources/translations/SonataMediaBundle.ja.xliff, Resources/translations/SonataMediaBundle.lt.xliff, Resources/translations/SonataMediaBundle.nl.xliff, Resources/translations/SonataMediaBundle.pl.xliff, Resources/translations/SonataMediaBundle.pt_BR.xliff, Resources/translations/SonataMediaBundle.ro.xliff, Resources/translations/SonataMediaBundle.ru.xliff, Resources/translations/SonataMediaBundle.sl.xliff, Resources/translations/SonataMediaBundle.uk.xliff, UPGRADE-4.0.md
```markdown
* Removed `wrap` property from `GalleryBlockService`
```
Removes an unused property form `GalleryBlockService`.
=> Remove 'wrap' property from GalleryBlock

Admin/BaseMediaAdmin.php, Admin/GalleryAdmin.php, Admin/GalleryHasMediaAdmin.php, composer.json
```markdown
- Fix deprecated usage of `Admin` class
```
The `Admin` class is deprecated since SonataAdminBundle `3.0`
=> use AbstractAdmin instead of deprecated Admin class

DependencyInjection/SonataMediaExtension.php, Resources/config/gaufrette.xml
Closes #987
```markdown
- `gaufrette.xml` is now compatible with Symfony 3
```
The Gaufrette configuration was using the deprecated functions setFactoryClass, setFactoryService and setFactoryMethod.
Fix source https://github.com/doctrine/DoctrineBundle/pull/381
=> make gaufrette config compatible with sf3

Extra/Pixlr.php
Closes #1051
```markdown
- Pixlr endpoints now use https
- Fixed mixed-content error when loading Pixlr editor under https
```
In sites under https, the Pixlr editor iframe didn't load, because of the hardcoded http protocol.
This commit hardcodes all Pixlr urls to https, to avoid mixed-content errors.
=> Switches Pixlr endpoints to https protocol

Resources/translations/SonataMediaBundle.es.xliff
I am targetting this branch, because this is a translation improvement.
```markdown
- Fixed media widget spanish translations
```
This fixes media widget spanish translations.
=> Fix media widget spanish translations

Provider/Pool.php
Refs https://github.com/sonata-project/SonataMediaBundle/pull/872
```markdown
- Deprecated `Pool::$downloadSecurities` for `Pool::$downloadStrategies` property
- Deprecated `Pool::addDownloadSecurity` for `Pool::addDownloadStrategy` method
- Deprecated `Pool::getDownloadSecurity` for `Pool::getDownloadStrategy` method
```
The name of `downloadSecurity` is wrong, because we use a `DownloadStrategyInterface`.
=> Rename downloadSecurity to downloadStrategy

Tests/Block/GalleryListBlockServiceTest.php, composer.json
I am targetting this branch, because this is a fix for the unit tests in the stable branch.
```markdown
- unit tests use the correct namespace in imports.
```
This fixes the imports in the test cases. The sub namespace `Tests` isn't public anymore.
=> Fixed wrong imports in tests

DependencyInjection/SonataMediaExtension.php, composer.json
I am targetting this branch, because this is a fix.
```markdown
- Added `sonata-project/block-bundle` dependency
```
Made the block bundle dependency surly optional.
=> Added missing block dependency

Form/Type/ApiMediaType.php, Form/Type/MediaType.php, Provider/BaseVideoProvider.php, Provider/FileProvider.php, Tests/Form/Type/AbstractTypeTest.php, Tests/Form/Type/ApiMediaTypeTest.php, Tests/Form/Type/MediaTypeTest.php, Tests/Provider/AbstractProviderTest.php, Tests/Provider/BaseProviderTest.php, Tests/Provider/DailyMotionProviderTest.php, Tests/Provider/FileProviderTest.php, Tests/Provider/ImageProviderTest.php, Tests/Provider/VimeoProviderTest.php, Tests/Provider/YouTubeProviderTest.php
I am targeting `3.x`, because it's the branch that should be compatible with Symfony 3+ but isn't.
```markdown
- Fixed `ApiMediaType::getParent` compatibility with Symfony3 forms
- Fixed `MediaType::buildForm` compatibility with Symfony3 forms
- Fixed `MediaType::getParent` compatibility with Symfony3 forms
- Fixed `BaseVideoProvider::buildEditForm` compatibility with Symfony3 forms
- Fixed `BaseVideoProvider::buildCreateForm` compatibility with Symfony3 forms
- Fixed `BaseVideoProvider:: buildMediaType` compatibility with Symfony3 forms
- Fixed `FileProvider::buildEditForm` compatibility with Symfony3 forms
- Fixed `FileProvider::buildCreateForm` compatibility with Symfony3 forms
- Fixed `FileProvider::buildMediaType` compatibility with Symfony3 forms
```
Forms are not compatible with …
=> Make forms compatible with Symfony3

Controller/Api/GalleryController.php
I am targeting 3.x, because 3.x was never working, to get it work.
Fixes #1080
```markdown
- Restored `ApiDoc` and `QueryParam` use statements in `Api/GalleryController`
```
Restores use statements to fix import exceptions in example in composer install. More details in the issue.
=> Fix imports in GalleryController

Resources/views/MediaAdmin/edit.html.twig
```markdown
- Fixed wrong html usage in edit template
```
The `center` tag doesn't exist anymore and the closing tags of `<tr>`s were missing.
=> Fixed wrong html

Resources/translations/SonataMediaBundle.de.xliff
I am targetting this branch, because this adds missing lables.
Some german translation keys were missing.
=> Fixed missing german translation

Provider/BaseVideoProvider.php, Provider/DailyMotionProvider.php, Provider/VimeoProvider.php, Provider/YouTubeProvider.php, Resources/doc/reference/creating_a_provider_class.rst, Tests/Provider/DailyMotionProviderTest.php, Tests/Provider/VimeoProviderTest.php, Tests/Provider/YouTubeProviderTest.php, UPGRADE-3.x.md
Rebase of https://github.com/sonata-project/SonataMediaBundle/pull/622
```markdown
- Created `getReferenceUrl` method for all video providers
```
Created a new method which returns the reference url of a video.
=> Add BaseVideoProvider::getReferenceUrl() method

Tests/CDN/CloudFrontTest.php, Tests/CDN/PantherPortalTest.php
I am targetting this branch, because it is a critical patch.
No changelog, users do not care about our tests (right?)
Merge ASAP :rotating_light: 
phpunit has no idea what the current namespace is.
This is why builds on most PRs are failing right now.
=> Use FQCNs when building mocks

Form/Type/MediaType.php, Tests/Form/Type/AbstractTypeTest.php, Tests/Form/Type/MediaTypeTest.php
Rebase of #806
```markdown
- The options `provider` and `context` are now required
```
The options must be set in order to show the media_type widget.
=> Made form options "provider" and "context" required in MediaType

DependencyInjection/Configuration.php, DependencyInjection/SonataMediaExtension.php, Resizer/SquareResizer.php, Resources/config/media.xml, Tests/DependencyInjection/ConfigurationTest.php, Tests/DependencyInjection/SonataMediaExtensionTest.php
I am targetting this branch, because this feature is BC.
Rebase of #721
Closes #700
```markdown
- Added config key to define default resizer
- Added config key to define default resizer adapter
```
Added two new config keys to define default resizer and resizer adapters to reduce duplicate configuration on each provider.
=> Add default resizer and default resizer adapter

Tests/Twig/Extension/MediaExtensionTest.php, Twig/Extension/MediaExtension.php
I am targetting this branch, even though this is major
```markdown
- Ability to provide custom attributes for a thumbnail
```
Reverting a BC-break is a BC-break, but I demand that this gets merged
anyway. If someone wants to restore this behavior, they will need to do it **properly**.
Fixes #1065
=> Revert a BC-break introduced by 22b20c5af

UPGRADE-3.x.md
I am targetting this branch, because it is upgrade not of this branch.
refs #1035
=> added upgrade note for deprecated container property

Model/CategoryManagerInterface.php
I am targetting this branch, because this is just a fix.
Fixes https://github.com/sonata-project/SonataMediaBundle/pull/1086
Fixes wrong phpdoc / interface method introduced in https://github.com/sonata-project/SonataMediaBundle/pull/1086
=> Fixed wrong phpdoc of #1086

Resources/translations/SonataMediaBundle.sl.xliff
I am targetting this branch, because there's only one change, in a translation file. It's just an omitted end tag, there's no BC-break.
```markdown
- Close an unclosed XML tag in a translation file. 
The last <target> tag, in <trans-unit id="form.label_class">,  was not closed in Resources/translations/SonataMediaBundle.sl.xliff.
=> Close an unclosed tag in translation file

DependencyInjection/SonataMediaExtension.php
I am targetting this branch, because this is BC
```markdown
- Deprecation warning for `addDownloadSecurity`
```
The method `addDownloadSecurity` is deprecated, we should use the new `addDownloadStrategy` in `SonataMediaExtension`
=> use addDownloadStrategy instead of deprecated addDownloadSecurity

Resources/views/MediaAdmin/list.html.twig
Partially closes sonata-project/SonataAdminBundle#4229
```markdown
- translation in twig templates now uses the twig translation filter
```
Removes deprecated translations calls from the `AdminInterface::trans` method.
=> Remove deprecated translation logic

Controller/Api/GalleryController.php, Controller/Api/MediaController.php, Tests/Controller/Api/GalleryControllerTest.php, Tests/Controller/Api/MediaControllerTest.php
Following [this](https://github.com/sonata-project/SonataUserBundle/pull/805) and [this](https://github.com/sonata-project/SonataClassificationBundle/pull/245). 
Closes https://github.com/sonata-project/SonataMediaBundle/issues/1056
```markdown
- Moved ApiDoc groups from string to array. 
- Moved FosRest groups from string to array and reimplemented the orderBy parameter enabling support for FosRestBundle>=2.0.
```
FosRestBundle>=2.0 requirest api groups declared as array and requires a new implementation of the orderBy parameter in the controller which has to be bc-compatible. This fix enable the support for both FosRest 1 and 2, following the two pull requests.
I uniformed the annotations in ApiDoc groups either. This seemed right to do because nelmio-apidoc usually expects groups as an …
=> Api groups moved from string to array

Resources/config/security.xml, Security/RolesDownloadStrategy.php, Tests/DependencyInjection/SonataMediaExtensionTest.php, Tests/Security/RolesDownloadStrategyTest.php
I am targetting this branch, because this branch an error which was introduced in #1165
```markdown
- Using the `SecurityContext` is not possible with Symfony >=2.8
```
```
[InvalidArgumentException]                                                                                                                                                    
Argument 2 should be an instance of Symfony\Component\Security\Core\Authorization\AuthorizationCheckerInterface or Symfony\Component\Security\Core\SecurityContextInterface  
```
Fix error after merge #1165
=> fix empty argument in RolesDownloadStrategy

Provider/MediaProviderInterface.php
I am targetting this branch, because this is pedantic.
```markdown
- fixed missing import for PHPdoc
```
Import is missing for https://github.com/core23/SonataMediaBundle/blob/92840a6fac0155030520ac02eeff5cdbd2d21ba1/Provider/MediaProviderInterface.php#L213.
=> Fixed wrong phpdoc

Resources/doc/reference/installation.rst, Resources/views/MediaAdmin/edit.html.twig, Tests/Block/Breadcrumb/BreadcrumbTest.php, composer.json
I am targetting this branch, because I think there is no BC break.
```markdown
- Media edit size calculations
- SonataIntlBundle dependency
```
SonataIntlBundle was only used to render sizes of images (300px x 400px) and image size (140 KB). We don't need to pass a filter to parse decimals on the image height and width since there are pixels. Depending on a bundle just to filter image size doesn't make much sense IMO, so I rewrited the size calculation as a macro without decimals.
On a image with size: 130,677 bytes
Before: 
350px x 500px (130,677o)
After:
350 x 500 (127.61 KB)
=> Refactor on media edit image size and measures, SonataIntlBundle is not needed anymore

Twig/Extension/FormatterMediaExtension.php, Twig/Extension/MediaExtension.php, composer.json
Refs #1183 
```markdown
- support for Twig 2.0
```
I was wondering, as there wasn't any dependency for twig...
=> compatibility with Twig 2.0

Admin/BaseMediaAdmin.php, Admin/GalleryAdmin.php, Model/Media.php, Resources/config/validation.xml
Closes #1115 #1101 #1148 #1111 
```markdown
- `cascade_validation` from `GalleryAdmin`
- Callback contraint is not a valid callable on Symfony 3
- `BaseAdmin` incorrectly retrieved `providerName`
```
Essentially the same as #1115 and #1148. But trying to do it in a BC way. Not sure about the Callback constraint, don't know if it is BC. Don't merge until we know.
=> Fixed compatibility with SF3

Resources/config/doctrine_mongodb_admin.xml, Resources/config/doctrine_orm_admin.xml, Resources/config/doctrine_phpcr_admin.xml
This is my first PR, I'm sorry if I do something in the wrong way !
I am targetting this branch, because it's a minor change that does not break BC.
```markdown
- An icon to admin menu (fa-image).
```
There was no image in the admin menu. So I added one :)
=> Add an icon to admin menu.

Controller/MediaController.php, Tests/Controller/MediaControllerTest.php, Tests/Helpers/PHPUnit_Framework_TestCase.php
Closes #1069 #1068 
```markdown
- Added `getRequest` method on controller for BC with Symfony 2.3+
```
This is essentially same as #1069. Since the user didn't answer, I created another PR with the same code.
It just fixes the compatibility with SF3, where you can't obtain request from the container, you have to use request_stack, available since SF2.8
~The build will fail until #1188 gets merged.~
=> Remove use of request from container directly

Tests/Entity/GalleryManagerTest.php, Tests/Entity/MediaManagerTest.php, composer.json
```markdown
- Fixed pager test with DatagridBundle 2.2.1
```
DatagridBundle change from `getRootAlias` to `getRootAliases`
=> Fixed tests

Block/GalleryBlockService.php, Block/GalleryListBlockService.php, Block/MediaBlockService.php, composer.json
```markdown
- Fixed BlockBundle deprecation messages
```
`BaseBlockService` is deprecated since 3.2 of SonataBlockBundle, changed to `AbstractBlockService`.
Not sure about why SonataBlockBundle is a require-dev. Should I add it to suggest?
=> Fixed BlockBundle deprecation messages

Admin/BaseMediaAdmin.php, Admin/GalleryAdmin.php, Admin/GalleryHasMediaAdmin.php, Admin/ORM/MediaAdmin.php, Block/FeatureMediaBlockService.php, Block/GalleryBlockService.php, Block/GalleryListBlockService.php, Block/MediaBlockService.php, Tests/Admin/BaseMediaAdminTest.php, Tests/Admin/GalleryAdminTest.php, Tests/Admin/GalleryHasMediaAdminTest.php, Tests/Admin/ORM/MediaAdminTest.php, Tests/Block/FeatureMediaBlockServiceTest.php, Tests/Block/GalleryBlockServiceTest.php, Tests/Block/MediaBlockServiceTest.php, Tests/DependencyInjection/ConfigurationTest.php, Tests/DependencyInjection/SonataMediaExtensionTest.php, Tests/Metadata/AmazonMetadataBuilderTest.php, Tests/Metadata/ProxyMetadataBuilderTest.php, Tests/Provider/AbstractProviderTest.php
```markdown
- Replaced form types for the FQCN's
```
Trying to make SF3 work with this bundle. I think this is mandatory for SF3, am I wrong? Because I get a lot of deprecations in SF2.8.
Is there a way, or it is implemented in another way in other sonata bundles to avoid all this code?
Also, do I need to replace DataGridMapper types and ListMapper types?
=> Replaced form types for the FQCN's

Admin/GalleryAdmin.php, DependencyInjection/Configuration.php, Model/Gallery.php, Resources/config/validation.xml, Resources/doc/reference/troubleshooting.rst, Tests/Validator/FormatValidatorTest.php, Validator/FormatValidator.php
I am targetting this branch, because this PR only change a file in the documentation so it's backward compatible.
Closes #1135
Documented the possibility to leave `formats` empty. This PR closes #1135
=> Documented empty `formats`

Admin/BaseMediaAdmin.php, Tests/Admin/BaseMediaAdminTest.php
BaseMediaAdmin incorrectly retrieved providerName from request
I am targeting this branch, because the bug was recently introduced in it in this PR #1191
Closes #1197
```markdown
- Incorrect access to providerName parameter in request in `Admin/BaseMediaAdmin.php`
```
This fixes a recently introduced bug where the providerName was incorrectly being read from the request object.
=> Fix providerName access from request object

Tests/Command/FixMediaContextCommandTest.php, Tests/Document/MediaManagerTest.php, Tests/Metadata/AmazonMetadataBuilderTest.php, Tests/Metadata/ProxyMetadataBuilderTest.php, Tests/PHPCR/MediaManagerTest.php, Tests/Provider/DailyMotionProviderTest.php, Tests/Provider/FileProviderTest.php, Tests/Provider/VimeoProviderTest.php, Tests/Provider/YouTubeProviderTest.php, Tests/Resizer/SquareResizerTest.php, composer.json
I am targetting this branch, because this only changes tests.
Every test is now executed, there are no skipped test. We decrease on test quantity because FixMediaContextCommandTest was extending CommandTest which is a Test class from symfony, not a TestCase.
Not sure about adding a deprecated dependency to required-dev but it was needed to test Amazon. Gauffrete itself uses it on its own Amazon class tho. Don't know if there are any other way of doing it.
=> Avoid skipped tests

Tests/Block/FeatureMediaBlockServiceTest.php, Tests/Block/GalleryBlockServiceTest.php, Tests/Block/GalleryListBlockServiceTest.php, Tests/Block/MediaBlockServiceTest.php
I am targetting this branch, because this only changes test.
This is pedantic. I found that Block Test were on a incorrect namespace. This PR just fixes that
=> Fixed namespace on test classes

Controller/MediaAdminController.php, Resources/views/MediaAdmin/list.html.twig, Tests/Controller/MediaAdminControllerTest.php, composer.json
Closes #1156 #1130 #1054 
```markdown
- Added test on `MediaAdminController`
- Media List is now filterable by Category again
```
Same fix as other PR's but with tests.
Not sure about all the mocks I have created. But it will be needed in order to fully test MediaAdminController.
I have done a little bit of refactor on MediaAdminController based on content in CRUDController (changed isGranted by checkAccess, removing some parameters,...)
=> Fixed category filter on Media List and Test MediaAdminController

Admin/GalleryAdmin.php, Block/MediaBlockService.php
I am targetting this branch, because this is a bugfix.
There was one missing change for the FQCN's on MediaBlockService.
I did a mistake on the GalleryAdmin: 'choice' is a Symfony type, not Sonata, and 'sonata_type_collection' is on CoreBundle. There is one CollectionType on AdminBundle but does not produce same behavior as before using 'sonta_type_collection'.
And from the PR: https://github.com/sonata-project/SonataMediaBundle/pull/1150, we removed a necessary end() call.
=> Fixed wrong FQCN's and added missing end() on GalleryAdmin

Resources/views/MediaAdmin/list.html.twig
I am targetting this branch, because is a bug fix.
```markdown
- Calling a macro without importing it is an error on twig 2.0
```
On Twig 2.0 is mandatory to import every macro you are going to use. When calling a macro inside another macro you also need to import it.
=> Calling a macro without being imported is an error on twig 2.0

Tests/Admin/BaseMediaAdminTest.php
Test are not passing on Symfony 2.3 and 2.7, because we did mock bad a method call.
=> Fixed build on 2.3 and 2.7

Admin/ORM/MediaAdmin.php
This PR tries to avoid deprecation warnings on Symfony2.8 with non FQCNs. 
I didn't spot it because it does not produce an error on Symfony3. There is some magic on Sonata that resolves this `'choice'`to its FQCN but only on SF3... since I don't like magic, I just replaced it with the correct value.
=> Remove deprecations from non FQCNs on form types

composer.json
I am targetting this branch, because this is BC and fixes a bug.
Closes #1215 
```markdown
- Optional dependency to SonataFormatterBundle is now on `^3.2`
```
SonataFormatterBundle 3.1.0 has a twig extension that implements
`\Twig_ExtensionInterface`. This is changed on 3.2.0 to extend `\Twig_Extension`.
This change allows us to support both twig 1.x and 2.x
=> Add conflict with SonataFormatterBundle <3.2

Admin/BaseMediaAdmin.php, Admin/GalleryAdmin.php, Admin/GalleryItemAdmin.php, Admin/ORM/MediaAdmin.php, Block/FeatureMediaBlockService.php, Block/GalleryBlockService.php, Block/GalleryListBlockService.php, Block/MediaBlockService.php, Controller/MediaController.php, DependencyInjection/SonataMediaExtension.php, Model/Media.php, Resources/config/gaufrette.xml, Resources/config/validation.xml, Tests/Admin/BaseMediaAdminTest.php, Tests/Controller/GalleryAdminControllerTest.php, Tests/Controller/MediaAdminControllerTest.php, Tests/Controller/MediaControllerTest.php, Tests/Form/Type/AbstractTypeTest.php, Tests/Provider/AbstractProviderTest.php, UPGRADE-4.0.md
I am targetting this branch, because this is removing compatibility with Symfony 2.3.
Closes #1057 
```markdown
- Changed `MediaController::downloadAction` signature to include Request as first parameter
- Changed `MediaController::viewAction` signature to include Request as first parameter
- Changed `MediaController::liipImagineFilterAction` signature to include Request as first parameter
```
I am removing unused lines of codes, used for symfony 2.3 compatibility on 3.x branch.
Also changing some controllers signatures to accept `$request`as a parameter.
=> Remove old Symfony 2.3 code

DependencyInjection/Compiler/AddProviderCompilerPass.php, DependencyInjection/SonataMediaExtension.php, UPGRADE-3.x.md
```markdown
- Removed an ugly hack to retrieve configuration on `AddProviderCompilerPass`
```
we were previously using an ugly hack that was relying on changing a definition
on the Extension class and then recovering it (and removing it after all) on the
compiler pass.
=> Changed how we retrieve configuration on AddProviderCompilerPass

Block/GalleryBlockService.php, Block/GalleryListBlockService.php, Block/MediaBlockService.php
I am targetting this branch, because it is BC compatible and it is a fix for typo error made [https://github.com/sonata-project/SonataMediaBundle/pull/1193](https://github.com/sonata-project/SonataMediaBundle/pull/1193).
Closes: N/A
- Fixed issue when using SonataMediaBundle blocks in conjunction with SonataPageBundle and page composer (Sonata sandbox)
Same issue as in: [https://github.com/sonata-project/SonataFormatterBundle/pull/235](https://github.com/sonata-project/SonataFormatterBundle/pull/235) -> it is not possible to use Media Bundle blocks because of wrong inheritance.
=> Fixing typo made in #1193

DependencyInjection/Compiler/AddProviderCompilerPass.php
I am targetting this branch, because this is typo error fix.
Closes #1218 for good.
File: DependencyInjection/Compiler/AddProviderCompilerPass.php, method getExtensionConfig() had typo error in working with $config(s) variable.
=> Fixing typo made in #1218

Resources/views/MediaAdmin/list.html.twig
I am targetting this branch, because this only changes a little thing on the media list.
There is a double padding on media list, because we are using col-* class two times.
I just removed the first's one padding.
BEFORE:
AFTER:
=> Fixed double padding on media list

Command/CleanMediaCommand.php, Tests/Command/CleanMediaCommandTest.php
I am targeting this branch, because this a bugfix.
Closes #1228 #954 
```markdown
- Replace missing `providers` column by `providerName` on clean command
```
Clean media command was not working because it was trying to access to a `providers` database column that does not exists. I Replaced it with `providerName`.
=> Replace missing providers column by providerName on clean command

composer.json
I am targeting this branch, because this change is BC and updates a vendor.
```markdown
- allow `knplabs/gaufrette v0.3.0`
```
Allows upgrading of knplabs/gaufrette to v0.3.0 with was just released 2 weeks ago.
=> allows knplabs/gaufrette v0.3.0

Provider/YouTubeProvider.php, Tests/Provider/YouTubeProviderTest.php
```markdown
- Change Youtube urls to use https
```
Youtube urls for fetching metadata and referenceUrl were using http. It is preferable to just use https.
Not sure if patch or pedantic
=> Move to https on Youtube urls

Extra/Pixlr.php
Working with SonataMediaBundle under a https protocol make pixrl url http://apps.pixlr.com not compatible with the platform.
```markdown
- fix protocol error from image url returned by pixlr when sonata is under https protocol
```
Allow non SSL pixlr url return
=> Allow non SSL pixlr url return

Resources/config/doctrine/Gallery.mongodb.xml.skeleton, Resources/config/doctrine/Gallery.orm.xml.skeleton, Resources/config/doctrine/Gallery.phpcr.xml.skeleton, Resources/config/doctrine/GalleryHasMedia.orm.xml.skeleton, Resources/config/doctrine/GalleryHasMedia.phpcr.xml.skeleton, Resources/config/doctrine/Media.mongodb.xml.skeleton, Resources/config/doctrine/Media.orm.xml.skeleton, Resources/config/doctrine/Media.phpcr.xml.skeleton, composer.json
I am targeting this branch, because my patch is fixing the bug, arisen due to the hardcoded class-path.
```markdown
- Fixed hardcoded paths to classes in `.xml.skeleton` files of config
```
Fixed some hardroded paths, which become invalid after enabling '--namespace' option in SonataEasyExtendsBundle's last release (https://github.com/sonata-project/SonataEasyExtendsBundle/releases/tag/2.2.0).
=> Fixed some hardcoded paths related to integration with SonataEasyExtendsBundle

Twig/Extension/MediaExtension.php
Change get_class() to get_called_class() to support extending the MediaExtension
I am targeting this branch, because I am trying to extend the MediaExtension twig extension to add my own custom twig methods.
Closes #1238
```markdown
- Ability to extend the MediaExtension class
```
=> Allow MediaExtension to be extended

Form/DataTransformer/ProviderDataTransformer.php, Form/DataTransformer/ServiceProviderDataTransformer.php, Form/Type/ApiMediaType.php, Form/Type/MediaType.php, Resources/config/api_form_doctrine_mongodb.xml, Resources/config/api_form_doctrine_orm.xml, Resources/config/api_form_doctrine_phpcr.xml, Resources/config/form.xml, Tests/Form/DataTransformer/ProviderDataTransformerTest.php, Tests/Form/DataTransformer/ServiceProviderDataTransformerTest.php, composer.json
I am targeting this branch (3.x), because this a fix for #1107 (and as per @jordisala1991's request).
Closes #1107. Before this PR, when there was an upload error (e.g., file too large), the DataTransformer was throwing an exception which was preventing the form from ever reaching the validation step. This was triggering a 500 Response instead of a 200 with a Form Error.
```markdown
- The DataTransformers and MediaTypes (both standard and API) now depend on `Psr\Log\LoggerInterface` in order to log any exception that could arise from `$provider->transform()`
- Optional dependency on `@logger`. If the service is unavailable the exception will be silently caught and discarded.
- Now we have form errors when uploaded files are too big!
```
Error message on upload fail (most of all, file too …
=> Fix #1107: Catch exception preventing correct handling of upload errors

Resources/doc/reference/installation.rst
People are confused because it looks as if the main configuration is
under the PHPCR section.
I am targeting this branch, because this is docs
=> Separate the persistence backend configuration

DependencyInjection/SonataMediaExtension.php
Twig nodes are template-compilation time only. There is no reason to inline them, they should be far from required all the time, isn't it?
Remove Twig nodes from classes to compile
=> Remove Twig nodes from classes to compile

composer.json
I am targeting this branch, because this change is BC and updates a vendor.
```markdown
- Allowed `jms/serializer-bundle ^2.0`
```
Allows upgrading jms/serializer-bundle to version 2.
=> Allow JMS serializer version 2

Resources/doc/reference/amazon_s3.rst
I am targeting this branch, because in v.2.x everything it's ok.
In version 2.x code block was properly formatted ( https://github.com/sonata-project/SonataMediaBundle/blob/2.x/Resources/doc/reference/amazon_s3.rst) but in version 3.x was not.
=> better formatting for code block in doc

Admin/BaseMediaAdmin.php, Controller/Api/MediaController.php, Controller/MediaController.php, DependencyInjection/Compiler/AddProviderCompilerPass.php, Extra/Pixlr.php, Model/Gallery.php, Provider/BaseProvider.php, Provider/BaseVideoProvider.php, Provider/FileProvider.php, Provider/ImageProvider.php, Provider/MediaProviderInterface.php, Resources/doc/reference/helpers.rst, Tests/Provider/ImageProviderTest.php, Thumbnail/FormatThumbnail.php, Thumbnail/LiipImagineThumbnail.php, Validator/FormatValidator.php
I am targeting this branch, because this feature is Backwards compatible.
```markdown
- The Image Provider returns responsive images to the twig media helper.
```
The Image providers getHelperProperties() function returns srcset and sizes attributes based on the current image's available sizes.
It only returns sizes smaller than the specified format. This way it is perfectly BC and the format let us control the returned sizes.
Browsers that don't support this feature will just serve the image defined by the 'format' option.
Passing a 'sizes' option to the media tag, easily overrides the predefined sizes to tailor for current template.
I'll update the docs if you are happy with the change.
=> Display responsive images with the ImageProvider

Provider/BaseProvider.php
I am targeting this branch, because it is patch.
```markdown
- Prevent file from being removed if an error occurred while deleting its database entry.
```
Moved deleting a file from file system from preRemove to postRemove.
Without it first deleting file and then trying to remove record. And if record, for example, has dependecies, it not deleted, but the file will already be deleted.
=> Fixed deleting a file if deleting throw the error.

Model/GalleryHasMedia.php
I am targeting this branch, because my little change is not a BC-break.
Add default values in `GalleryHasMedia` model without `__construct` as `Media` model [does](https://github.com/sonata-project/SonataMediaBundle/blob/3.x/Model/Media.php).
With this little change no one needs to rewrite the `__construct` to setup different default `position` and `enabled` values.
[Default value in Doctrine](http://docs.doctrine-project.org/en/latest/reference/faq.html#how-can-i-add-default-values-to-a-column)
Thanks
=> Add default values in without __construct method

DependencyInjection/SonataMediaExtension.php
I am targeting this branch, because this fix a deprecation warning and is BC.
```markdown
- deprecation notices related to `addClassesToCompile`
```
Only call addClassesToCompile on PHP < 7.0 since it is deprecated and doesn't improve performances with PHP >= 7.0
=> Only add classes to compile on PHP < 7.0

DependencyInjection/SonataMediaExtension.php, UPGRADE-3.x.md
Closes #1240
```markdown
- Added `'onDelete' => 'CASCADE'` for mapping from GalleryHasMedia to Media and Gallery
=> Fix deleting a media if included in a gallery

Tests/Twig/Extension/MediaExtensionTest.php
I am targeting this branch, because it is bug fix.
There is no need to describe this in changelog
`Twig_TemplateInterface` is deprecated since Twig 1.12 and removed in Twig 2.0. Composer require minimum Twig 1.28 so it is ok. Fix warning in PHP 7.x platform tests where Twig 2 is used (because require PHP 7.x).
```
There was 1 warning:
1) MediaExtensionTest::testThumbnailHasAllNecessaryAttributes
Cannot stub or mock class or interface "Twig_TemplateInterface" which does not exist
```
=> Fix unit test warning if Twig 2.x is used

DependencyInjection/SonataMediaExtension.php, Resources/config/security.xml, Resources/doc/reference/security.rst, Tests/DependencyInjection/SonataMediaExtensionTest.php
I am targeting this branch, because this PR make SonataMediaBundle compatible with configurable roles (see subject section).
```markdown
- Use SonataAdminBundle configuration to configure bundle services
```
This PR is related to https://github.com/sonata-project/SonataAdminBundle/pull/4548. We are introducing the ability to configure sonata "main" roles under the section `security` of SonataAdminBundle.
Without this PR, changing the SonataAdminBundle `ROLE_SUPER_ADMIN` to something else will break the role-based media download strategy.
No breaking changes are introduced and this may be merged at anytime.
=> Use SonataAdminBundle configuration to configure bundle services

Command/CleanMediaCommand.php, Command/RemoveThumbsCommand.php, Tests/Command/RemoveThumbsCommandTest.php, composer.json
I am targeting this branch, because my patch is fixing the bug existing in this branch.
Closes #1258 
```markdown
- Silent `sonata:media:remove-thumbnails` command when running this command without arguments.
```
I'have fixed the call to undefined helper 'dialog'. Intead of 'dialog' the 'question' helper is used.
=> RemoveThumbsCommand dialog error fix

Command/SyncThumbsCommand.php
I am targeting this branch, because of sf3 compatibility fix.
```markdown
- Sf3 compatibility on the sync-thumbnails command (dialog helper)
```
We had some issues with our images after adding a new image format, but we can't run the command as we use sf 3.3
=> Sf3 compatbility fix for sync-thumbnails command

src/Controller/GalleryAdminController.php, src/Controller/MediaAdminController.php, tests/Controller/GalleryAdminControllerTest.php, tests/Controller/MediaAdminControllerTest.php
I am targeting this branch, because it fixes a bug (Admin controllers do not work with Symfony 3.4)
```markdown
- Use FormRenderer runtime to maintain compatibility with Symfony 3.4
```
Symfony 3.4 deprecates `TwigRenderer` (TwigBridge) in favour of `FormRenderer` (Form component). While the old class is still available, it is not registered as a Twig runtime anymore. ([See this related changeset in the TwigBridge component.](https://github.com/symfony/symfony/pull/23437/files#diff-5eb0532c96734f6e23428e921225b2f0))
`MediaAdminController` and `GalleryAdminController` try to call this runtime by class name, which throws an Exception (tested with Symfony 3.4-BETA4).
```
Twig_Error_Runtime:
Unable to load the "Symfony\Bridge\Twig\Form\TwigRenderer" runtime.
at …
```
=> Use FormRenderer runtime to maintain compatibility with Symfony 3.4

docs/reference/helpers.rst, src/Provider/ImageProvider.php, tests/Provider/ImageProviderTest.php
I am targeting this branch, because this was a missing feature.
```markdown
- Added option to set the img `srcset` tag by giving it an array of format names.
```
Frontend developers need the possibility to explicitly choose which formats need to be available in the srcset tag. This was currently achievable by combining the *media* tag with the *path* tag, but this is not user friendly and hardly maintainable.
Instead I created the possiblity to give the srcset tag an array of format names, which will be converted to the correct URL and settings for each format.
=> Set img srcset tag by format names

src/Resources/translations/SonataMediaBundle.bg.xliff, src/Resources/translations/SonataMediaBundle.de.xliff, src/Resources/translations/SonataMediaBundle.en.xliff, src/Resources/translations/SonataMediaBundle.es.xliff, src/Resources/translations/SonataMediaBundle.fa.xliff, src/Resources/translations/SonataMediaBundle.fi.xliff, src/Resources/translations/SonataMediaBundle.fr.xliff, src/Resources/translations/SonataMediaBundle.hu.xliff, src/Resources/translations/SonataMediaBundle.it.xliff, src/Resources/translations/SonataMediaBundle.ja.xliff, src/Resources/translations/SonataMediaBundle.lt.xliff, src/Resources/translations/SonataMediaBundle.nl.xliff, src/Resources/translations/SonataMediaBundle.pl.xliff, src/Resources/translations/SonataMediaBundle.pt_BR.xliff, src/Resources/translations/SonataMediaBundle.ro.xliff, src/Resources/translations/SonataMediaBundle.ru.xliff, src/Resources/translations/SonataMediaBundle.sl.xliff, src/Resources/translations/SonataMediaBundle.uk.xliff, src/Resources/views/Block/block_gallery.html.twig
I am targeting this branch, because this fixes a bug with twig 2.0.
```markdown
- fixed bug against twig 2.0 as `translationBundle` cannot be null
```
After upgrading to twig 2.0 I got some errors from following templates. 
As I understand ```sonata_template_box``` requires 2 parameters now in order to be compliant, so I added the translation domain in this PR to address the issue.
```
- The template "SonataMediaBundle:Gallery:index.html.twig" contains an error: Using "null" for the value of node "translationBundle" of "Sonata\CoreBundle\Twig\Node\TemplateBoxNode" is not supported. You must pass a Twig_Node instance.
- The template "SonataMediaBundle:Gallery:view.html.twig" contains an error: Using "null" for the value of node "translationBundle" of …
```
=> Fix sonata_template_box templates compatibility with twig 2.0

src/Resources/translations/SonataMediaBundle.ru.xliff
```markdown
- Added russian translations
```
Some keys of russian translation were missing. Some of the keys that were present had stubs instead of translations. Russian translations have been added for both of these cases.
=> Added russian translations

src/Provider/ImageProvider.php, tests/Provider/ImageProviderTest.php
I am targeting this branch, because when defining srcsets, the src format needs to be added again.
```markdown
- Added automatically adding src format to srcset
```
I just noticed that when defining your srcset formats, the src format itself wasn't printed. Now it's automatically added if it wasn't done by the user.
=> Always put src format in srcset

src/Resizer/SquareResizer.php, tests/Resizer/SquareResizerTest.php
I am targeting this branch, because the wrong size is returned for a cropped image.
```markdown
- Return size after resize in cropping flow, not just the cropped dimensions
```
Function `getBox` is supposed to return the dimensions for given media with applied settings. However, when an image is cropped, that size was returned directly. Resizing is the next step and should also be done before returning the actual size.
=> Return correct size cropped image

src/Controller/Api/GalleryController.php, src/Controller/Api/MediaController.php
Refs #1267
```markdown
- FOSRest-related deprecations
```
Apparently setMaxDepth was a misnomer.
See https://github.com/FriendsOfSymfony/FOSRestBundle/pull/1506
=> Call new FOSRest API

composer.json
The bundle was added here: https://github.com/sonata-project/SonataMediaBundle/pull/1259 without a good reason. It is making SF 4 compatibility impossible, since it won't update to symfony4 because of https://github.com/symfony/maker-bundle
To sumarize, not a good idea to add a dependency on a bundle that has no future
=> Remove unnecesary bundle

src/Resources/views/GalleryAdmin/list.html.twig
I am targeting this branch, because it's just a missing translation.
```markdown
- Selected gallery context is now translated just like in the dropdown.
```
This fixes a small translation bug: The name of the selected gallery context remained untranslated, although the options in the dropdown list are being translated correctly.
=> Selected gallery context remained untranslated in dropdown

src/Admin/BaseMediaAdmin.php, src/Admin/GalleryAdmin.php, src/Admin/GalleryHasMediaAdmin.php, src/Admin/ORM/MediaAdmin.php, src/Block/FeatureMediaBlockService.php, src/Block/GalleryBlockService.php, src/Block/GalleryListBlockService.php, src/Block/MediaBlockService.php, src/DependencyInjection/SonataMediaExtension.php, src/Form/DataTransformer/ProviderDataTransformer.php, src/Form/DataTransformer/ServiceProviderDataTransformer.php, src/Form/Type/ApiMediaType.php, src/Form/Type/MediaType.php, src/Model/Media.php, src/Provider/BaseVideoProvider.php, src/Provider/FileProvider.php, src/Resources/config/gaufrette.xml, tests/Admin/BaseMediaAdminTest.php, tests/Controller/GalleryAdminControllerTest.php, tests/Controller/MediaAdminControllerTest.php, tests/Controller/MediaControllerTest.php, tests/Entity/GalleryManagerTest.php, tests/Form/Type/AbstractTypeTest.php, tests/Form/Type/MediaTypeTest.php, tests/Provider/AbstractProviderTest.php, tests/Provider/FileProviderTest.php, tests/Security/RolesDownloadStrategyTest.php, tests/Validator/FormatValidatorTest.php
Removing old code that never gets executed because we dropped SF 2.3 to 2.7
=> Drop old Symfony and PHP code

tests/Block/GalleryListBlockServiceTest.php, tests/Command/CleanMediaCommandTest.php, tests/Command/FixMediaContextCommandTest.php, tests/Controller/Api/GalleryControllerTest.php, tests/Controller/Api/MediaControllerTest.php, tests/Form/DataTransformer/ProviderDataTransformerTest.php, tests/Form/Type/AbstractTypeTest.php, tests/Form/Type/ApiMediaTypeTest.php, tests/Form/Type/MediaTypeTest.php, tests/Metadata/ProxyMetadataBuilderTest.php, tests/Provider/AbstractProviderTest.php, tests/Provider/DailyMotionProviderTest.php, tests/Provider/FileProviderTest.php, tests/Provider/PoolTest.php, tests/Provider/VimeoProviderTest.php, tests/Provider/YouTubeProviderTest.php, tests/Resizer/SimpleResizerTest.php, tests/Resizer/SquareResizerTest.php
I am targeting this branch, because it's BC.
```markdown
- Replaced `getMockBuilder` with `createMock` where it was possible
```
=> Use createMock in test files where it's possible

src/Resources/config/doctrine_orm.xml, src/Resources/config/provider.xml
I am targeting this branch, because this is a fix.
Closes #1364
```markdown
- Make services public
```
While I was fixing the documentation I encountered an error:
> The "sonata.media.pool" service or alias has been removed or inlined when the container was compiled.
Making `sonata.media.pool` public fixed the problem, I saw there is a similar issue with the same problem (#1364) so I made that service also public.
=> Make services public

src/DependencyInjection/SonataMediaExtension.php, src/Resources/config/command.xml
I am targeting this branch, because this is a BC fix.
```markdown
- Commands not working on symfony4
```
On symfony4 commands are not working as they are not registered as a services, this fixes it.
=> Commands as services

composer.json, src/Metadata/AmazonMetadataBuilder.php
Closes #1160 
Closes #1294 
```markdown
- `AmazonMetadataBuilder` now relies on Psr7 mimeType guesser
```
Changed old code that relied on a guzzle concrete version by the Psr7 code. It is a small library that is also used by http-plug, so won't conflict with that when we decide to move there.
=> use Psr7 mimeType guesser

composer.json
```markdown
- Removed `SonataNotificationBundle` as a required dependency
```
It was added here (on composer.json and code): 
PR: https://github.com/sonata-project/SonataMediaBundle/pull/151/files
Commit: https://github.com/sonata-project/SonataMediaBundle/commit/fa34e9e9c93c2a3ea6a7aab02463eae78c5c7f82
It was always made optional (not loaded if bundle is not present), so no need to make it a hard requirement on composer
=> NotificationBundle is an optional dependency

composer.json, docs/reference/api.rst, src/Controller/Api/GalleryController.php, src/Controller/Api/MediaController.php
```markdown
- Removed compatibility with older versions of FOSRestBundle (<2.1)
```
Since dropping a dependency is not a BC break, this is a good start, because we are doing a lot of code just to keep compat with FOSRest 1.
Those are the PR adding this code, to check if I did correctly or not: https://github.com/sonata-project/SonataMediaBundle/pull/1071 https://github.com/sonata-project/SonataMediaBundle/pull/1155 https://github.com/sonata-project/SonataMediaBundle/pull/1339
=> Remove compatibility with FOSRest < 2.1

docs/reference/creating_a_provider_class.rst, src/Provider/VimeoProvider.php, tests/Provider/VimeoProviderTest.php
I am targeting this branch, because it doesn't break anything.
Closes: no issue created
```markdown
- Changed Vimeo endpoint to https
```
Use https endpoint for Vimeo because of security reasons.
=> Use https urls for vimeo api endpoint

docs/reference/form.rst
I am targeting this branch, because this is docs.
`@SonataMedia/Form/media_widgets.html.twig` template must be added to `twig.form_themes`, not to `twig.form.resources`
=> Fix outdated twig docs

src/Command/SyncThumbsCommand.php
The following error occurred when i ran the sonata:media:sync-thumbnails command with PHPCR or ODM document mapper.
`Error thrown while running command "sonata:media:sync-thumbnails". Message: "Call to undefined method Sonata\MediaBundle\PHPCR\MediaManager::getEntityManager()"`
https://github.com/sonata-project/SonataMediaBundle/blob/8ca7f8447f439d79d8b42aaa1d25683c769cf5b1/src/Command/SyncThumbsCommand.php#L144
If you use PHPCR then $this->getMediaManager() is Sonata\CoreBundle\Model\BasePHPCRManager and this class does not have getEntityManager() method.
Same as in the Sonata\CoreBundle\Model\BaseDocumentManager class when you use ODM.
But the ORM, ODM and the PHPCR manager class extends same Sonata\CoreBundle\Model\BaseManager class, which has getObjectManager() method.
Changing …
=> SyncThumbsCommand PHPCR, ODM manager fix

src/Resources/views/Form/media_widgets.html.twig
Closes #1369 
```markdown
- Fixed widget template for MediaType as a child form type
```
When `Sonata\MediaBundle\Form\Type\MediaType` is a child of some other form type, `Sonata\AdminBundle\Form\Extension\Field\Type\FormTypeFieldExtension` [sets](https://github.com/sonata-project/SonataAdminBundle/blob/3.x/src/Form/Extension/Field/Type/FormTypeFieldExtension.php#L78) `$view->vars['sonata_admin_enabled'] = true;` and at the same time `$view->vars['sonata_admin']['admin']` is false!
This PR adds one additional check `... and sonata_admin.admin is not same as(false)` to widget template for MediaType.
=> Fix widget template for MediaType as a child form type

src/DependencyInjection/Configuration.php, src/DependencyInjection/SonataMediaExtension.php, src/Exception/NoDriverException.php, src/Generator/NoDriverGenerator.php, src/Model/NoDriverManager.php, src/Resources/config/no_driver.xml, src/Resources/config/no_driver_admin.xml, tests/Generator/NoDriverGeneratorTest.php, tests/Model/NoDriverManagerTest.php
Closes #1419
```markdown
- A db_driver configuration parameter is optional now with 'no_driver' default value
```
To create a recipe for Symfony Flex, it should be possible to create a default configuration, that allows to run `cache:clear` without errors (see https://github.com/sonata-project/dev-kit/issues/409) A default value for `db_driver` configuration parameter will allow this.
If this PR will be accepted, a default configuration, i.e. a recipe for `sonata-media/media-bundle` could be like this (please fix me, it there something wrong here; may be `providers` or `formats` sections should be changed to more commonly used?):
```yaml
sonata_media:
default_context: default
contexts:
default:
providers:
- sonata.media.provider.dailymotion …
```
=> Make a db_driver configuration parameter optional with no_driver default value

src/Admin/GalleryAdmin.php, src/Controller/Api/GalleryController.php, src/Model/Gallery.php, src/Model/GalleryInterface.php, src/Model/GalleryMediaCollectionInterface.php, src/PHPCR/BaseGallery.php
Fixes #1396, closes #1394, and closes #1370
```markdown
- Added `Sonata\MediaBundle\Model\Gallery::addGalleryHasMedia` and `Sonata\MediaBundle\Model\Gallery::removeGalleryHasMedia` to properly manage collections.
- Deprecated `Sonata\MediaBundle\Model\Gallery::addGalleryHasMedias` because adder must use singular naming.
- Removed old hacks in GalleryAdmin setting galleryHasMedia collection.
```
Unlike PRs #1394 and #1370 this is a proper fix which eliminates the core reason of that collection behavior and removes hacks which were added into GalleryAdmin. It also maintains backwards compatibility by keeping an old addGalleryHasMedias method which is marked as deprecated.
If you look into …
=> Bugfix - galleryHasMedia collection is removed on Gallery update

src/Controller/GalleryAdminController.php, src/Controller/MediaAdminController.php, tests/Controller/Api/GalleryControllerTest.php
I am targeting this branch, because is Deprecation and BC.
```markdown
- Make `Sonata\MediaBundle\Controller\MediaAdminController` use `renderWithExtraParams`
instead of the deprecated `render` from `Sonata\AdminBundle\Controller\CRUDController`
- Make `Sonata\MediaBundle\Controller\GalleryAdminController` use `renderWithExtraParams`
instead of the deprecated `render` from `Sonata\AdminBundle\Controller\CRUDController`
```
Stop using Sonata\AdminBundle\Controller\CRUDController::render and use renderWithExtraParams
=> Stop using Sonata\AdminBundle\Controller\CRUDController::render and use renderWithExtraParams

src/Resources/config/category.xml, src/Resources/config/doctrine_mongodb.xml, src/Resources/config/doctrine_orm.xml, src/Resources/config/doctrine_phpcr.xml, src/Resources/config/gaufrette.xml, src/Resources/config/provider.xml
I am targeting this branch, because is a patch and backwards compatible.
Closes #1379
```markdown
- `sonata.media.manager.media` is now `public`
- `sonata.media.manager.gallery` is now `public`
- `sonata.media.metadata.proxy` is now `public`
- `sonata.media.metadata.amazon` is now `public`
- `sonata.media.metadata.noop` is now `public`
- `sonata.media.provider.image` is now `public`
- `sonata.media.provider.file` is now `public`
- `sonata.media.provider.youtube` is now `public`
- `sonata.media.provider.dailymotion` is now `public`
- `sonata.media.provider.vimeo` is now `public`
```
Set providers, metadata and manager services public so applications using SonataMediaBundle can upgrade to Symfony 4.0.
=> Make providers, metadata, and managers services public

src/Admin/BaseMediaAdmin.php, src/Admin/GalleryAdmin.php
I am targeting this branch, because this is BC patch.
See https://github.com/sonata-project/media-orm-pack/issues/3
```markdown
- Force use existing translation strings for Media/Gallery breadcrumbs in Admin panel
```
If a last part of Media/Gallery class name differs from `Media` or `Gallery`, then `Admin` will try to use non-existing translation strings for breadcrumbs instead of `breadcrumb.link_media_list` or `breadcrumb.link_gallery_create`, i.e. it will use `breadcrumb.link_sonata_media_media_list` for `SonataMediaMedia` and `breadcrumb.link_sonata_media_gallery_create` for `SonataMediaGallery` classes.
With this PR `Admin` will be forced to use existing translation strings.
=> Force use existing translation strings for Media and Gallery

composer.json
I am targeting this branch, because I don't know if it's consider as a BC break to update a vendor.
```markdown
- Allow Gaufrette 0.6
```
=> Allow gaufrette 0.6

src/Provider/BaseProvider.php
I am targeting this branch, because the resized images was not deleted when the origine image was deleted.
- Remove all resized images when the origine image was deleted.
```markdown
- Moved a code block from BaseProvider::postRemove to BaseProvider::preRemove
```
We should delete all resized images when the original image has been removed, but sonata media just to clear the original image and keep the other resized images in the upload folder. So this pull request will fix this problem by changing some codes in the class BaseProvider.
=> Remove all thumbnails before removing media

src/Provider/FileProvider.php
I am targeting this branch, because it adds helpful getters to FileProvider class.
```markdown
- Added getters for `allowedExtensions` and  `allowedMimeTypes` properties
```
Useful when we inject the provider in twig.
=> Add getters to FileProvider

docs/reference/creating_a_provider_class.rst, src/Model/Gallery.php, src/Model/GalleryHasMedia.php, src/Model/GalleryHasMediaInterface.php, src/Model/GalleryInterface.php, src/Model/MediaInterface.php, src/Provider/BaseProvider.php
```markdown
- Fixed case typo for \DateTime 
```
Some PHPDoc fixes and one typo fix.
=>  Fixed wrong PHPDoc 

src/DependencyInjection/SonataMediaExtension.php, tests/DependencyInjection/SonataMediaExtensionTest.php
I am targeting this branch  3.x, because it used for backward compatible PRs.
```Markdown
- S3 Connection without use of credentials (access and secret keys) but with IAM roles (Amazon instances must have been configured with it). 
```
To connect to an Amazon S3, you can use IAM role (cf. https://docs.aws.amazon.com/sdk-for-php/v3/developer-guide/guide_credentials.html#instance-profile-credentials). But sonata media always set credentials has an array with secret and acces keys.
Sonata admin could send a credential set at `false` if  `filesystem.s3.accessKey` and `filesystem.s3.secretKey` are `null` in sonata_media configuration. So aws_sdk set an empty Credentials object (cf. https://github.com/aws/aws-sdk-php/blob/master/src/ClientResolver.php#L405)  and use IAM roles.
=> Connection to S3 without credentials but with IAM role

src/DependencyInjection/SonataMediaExtension.php, tests/DependencyInjection/SonataMediaExtensionTest.php
I am targeting this branch, because this is a BC compatible fix.
```markdown
- Fixed S3 credentials set to false when no credentials are provided
```
The PR #1431 added the possibility to configure S3 without credentials in order to rely on the IAM roles of instances for authorizations. 
However, setting the credentials key to false tells AWS to **not** use any credentials in the requests. To use the default credential provider chain, and let the SDK do proper authent with env vars or IAM roles, we must not provide the credential option as explained in the [SDK documentation](https://docs.aws.amazon.com/sdk-for-php/v3/developer-guide/guide_configuration.html#credentials).
=> Allow usage of AWS default credential provider chain for S3

src/DependencyInjection/Compiler/AddProviderCompilerPass.php, tests/DependencyInjection/Compiler/AddProviderCompilerPassTest.php
I am targeting this branch, because this is backwards compatible bug fix.
```markdown
- Bug where an extension config with unresolved parameters was processed in a compiler pass
```
Unresolved config was processed in `AddProviderCompilerPass`. If some config value wasn't set directly, but `'%parameter%'` was passed, this parameter value wasn't properly resolved and was processed as `'%parameter%'` string. This led to issues particularly when using parameter to set formats in a context. Configuration expected formats value to be an array, but since parameter was not resolved, it was actually a string and processing configuration failed.
=> Resolve config parameters before returning config.

src/Provider/ImageProvider.php
I am targeting this branch, because it removes useless duplicated code. The code is already the same in the `FileProvider::getReferenceImage` parent method
=> Remove useless duplicated code

composer.json
Closes https://github.com/sonata-project/SonataFormatterBundle/issues/367
```markdown
- Prevent incompatible `sonata-project/formatter-bundle` 4 from being installed
```
The media bundle is not yet compatible with it, there is at least
`FormatterMediaExtension::getTwigExtension()` that needs a signature
change.
=> Prevent formatter v4 from being installed

composer.json
I am targeting this branch, because this is a vendor update.
```markdown
- Allow Gaufrette 0.7
```
=> Allow gaufrette 0.7

src/Twig/Extension/FormatterMediaExtension.php
```markdown
- Added missing methods to `FormatterMediaExtension`
```
When decoupling this bundle from the formatter bundle (https://github.com/sonata-project/SonataMediaBundle/pull/1478), some methods were missing.
=> Fixed media formatter

src/Model/MediaManagerInterface.php
The deprecation notice is wrong. You couldn't use `ManagerInterface` in any case.
```markdown
- Undeprecated `MediaManagerInterface`
```
=> Undeprecated MediaManagerInterface

src/Twig/Extension/MediaExtension.php
The thumbnail or path function is used for Sonata Media and the media is null an exception is thrown
Closes #1517 
```markdown
- crashes on pages with null medias
```
=> Remove exception when the media is null

docs/reference/helpers.rst, src/Provider/ImageProvider.php, src/Resizer/SimpleResizer.php, src/Resources/views/Provider/view_image.html.twig, tests/Provider/ImageProviderTest.php, tests/Resizer/SimpleResizerTest.php
This PR adds an additional configuration option `picture` to the media helper, that can act as an alternative to `srcset` and `sizes` and will trigger rendering of a `<picture>` element instead of an `<img>`.
I am targeting this branch, because the PR offers an additional configuration option to the media helper. It is backwards compatible because media helper output remains unchanged if the new option is not used.
Closes #1543
```markdown
- Added configuration option for the media helper to generate a <picture> instead of <img>
- SimpleResizer::computeBox() will return the size of the resulting image instead of just the scaled image before the cropping step.
```
=> Add support for <picture> element in media helper

src/Model/Media.php
This PR prevent `TypeError: pathinfo() expects parameter 1 to be string, null given` that occurs on media upload when validation fails for another field
I am targeting this branch, because it's bug fix.
Closes #1560 
```markdown
- `TypeError` on media upload when validation fails for another field
```
=> Fix null provider reference

src/Controller/MediaAdminController.php, tests/Controller/MediaAdminControllerTest.php
I wrongly assumed `$theme` could only be a string in a previous PR.
Fixes #1557
```markdown
- Crash about `setFormTheme` when viewing the media list
```
```shell
composer config repositories.greg0ire vcs https://github.com/greg0ire/SonataMediaBundle
composer require sonata-project/media-bundle "dev-fix-wrong-type-hint as 3.18.1"
```
=> Use array type hint for theme

src/Model/CategoryManager.php
I am targeting this branch, because branch 3.x is currently broken.
```markdown
- return type for `CategoryManager::find()`
```
=> CategoryManager - wrong type hint

src/Provider/FileProvider.php, tests/Provider/FileProviderTest.php
I am targeting this branch, because it's a bug fix.
```markdown
- Fix file too big message not displayed when `$media->getBinaryContent()->getClientSize()` return `null`
```
=> Fix php upload_max_filesize message not showing when size is null

composer.json
Allow to use "jms/serializer-bundle:^3.0"
I am targeting this branch, because the version 3 of jms/serializer-bundle is now stable and it is compatible with the implementation in this branch.
```markdown
- Added compatibility with "jms/serializer-bundle:^3.0"
```
=> [Dependencies] Allow "jms/serializer-bundle:^3.0"

src/Provider/BaseVideoProvider.php, tests/Provider/DailyMotionProviderTest.php, tests/Provider/VimeoProviderTest.php, tests/Provider/YouTubeProviderTest.php
In function `getMetadata` in class `BaseVideoProvider` there were an error to throw an exception (line: 212) because this `RuntimeException` receive `null` to second parameter but this class is strict type and this exception normally receive a long, 
```markdown
- Value of code to throw RuntimeException when url of video throw an exception
```
=> fix(exception): fix value of code exception to respect strict type

src/Model/GalleryMediaCollectionInterface.php
- The GalleryMediaCollectionInterface refereced the old
GalleryHasMediaInterface wich was migrated to GalleryItemInterface.
- The old reference was repalced with the new interface
because: Branch `3.x` uses the old  GalleryHasMediaInterface
branch master replaced the old interface with the new one. The Interface: GalleryMediaCollectionInterface was forgotten in this migration
Closes #{put_issue_number_here}
On branch master
Changes to be committed:
- modified:   src/Model/GalleryMediaCollectionInterface.php
```markdown
src/Model/GalleryMediaCollectionInterface.php
src/Model/GalleryMediaCollectionInterface.php
```
=> [Bug]: GalleryMediaCollectionInterface references non existant Interface

src/Resources/config/doctrine_mongodb_admin.xml, src/Resources/config/doctrine_orm_admin.xml, src/Resources/config/doctrine_phpcr_admin.xml, src/Resources/config/routing/gallery.xml, src/Resources/config/routing/media.xml
Modernize references to controllers in order to avoid deprecated syntaxes.
I am targeting this branch, because these changes are BC.
```markdown
- Updated "_controller" attribute for routes which were using deprecated syntax.
```
=> Modernize references to controllers

composer.json, src/Resources/views/MediaAdmin/edit.html.twig, src/Resources/views/MediaAdmin/list.html.twig
Bump "twig/twig" to "^2.9" in order to replace usages of deprecated features.
I am targeting this branch, because the changes are considered BC.
```markdown
- Bumped "twig/twig" dependency to "^2.9";
- Changed usages of `{% spaceless %}` tag, which is deprecated as of Twig 1.38 with `{% apply spaceless %}` filter;
- Changed usages of `{% for .. if .. %}`, which is deprecated as of Twig 2.10 with `filter` filter'.
```
Follow up of sonata-project/SonataAdminBundle#5576.
=> Bump "twig/twig" to "^2.9" in order to replace usage of deprecated features

composer.json
Update constraint for "twig/twig" to ^2.10.
See https://github.com/sonata-project/SonataAdminBundle/pull/5576#issuecomment-509216140.
```markdown
- Possibility to resolve Twig dependency to versions that don't support arrow functions on Twig filters.
```
=> Update constraint for "twig/twig" to ^2.10

src/Twig/Extension/FormatterMediaExtension.php, src/Twig/Extension/MediaExtension.php, src/Twig/Node/MediaNode.php, src/Twig/Node/PathNode.php, src/Twig/Node/ThumbnailNode.php, src/Twig/TokenParser/MediaTokenParser.php, src/Twig/TokenParser/PathTokenParser.php, src/Twig/TokenParser/ThumbnailTokenParser.php, tests/Controller/GalleryAdminControllerTest.php, tests/Controller/MediaAdminControllerTest.php, tests/Twig/Extension/MediaExtensionTest.php
Use Twig namespaced classes where possible.
The non namespaced classes were left intact at public method signatures where they can't be replaced.
```markdown
- Using deprecated `\Twig_` classes without namespace.
```
=> Use Twig namespaced classes where possible

src/Command/AddMassMediaCommand.php, src/Twig/Extension/MediaExtension.php
Remove some non required function calls (`call_user_func()`, `get_called_class()`).
=> Remove some non required function calls

src/Resources/views/MediaAdmin/list_image.html.twig
Respect inherited "field_description.options.route.name" value at `list_image.html.twig`.
```markdown
- Respect "field_description.options.route.name" value at `list_image.html.twig` instead of using hardcoded "edit".
```
=> Respect inherited "field_description.options.route.name" value at `list_image.html.twig`

src/Resources/config/seo_block.xml
I am targeting this branch, because this is technically a BC break, because it removes breadcrumb blocks from the page composer, but no one should ever used it.
```markdown
- Add `breadcrumb` as default context for seo blocks
```
=> Add breadcrumb context to seo blocks

src/Twig/Extension/MediaExtension.php, src/Twig/Node/MediaNode.php, src/Twig/Node/PathNode.php, src/Twig/Node/ThumbnailNode.php, src/Twig/TokenParser/MediaTokenParser.php, src/Twig/TokenParser/PathTokenParser.php, src/Twig/TokenParser/ThumbnailTokenParser.php
Use Twig namespaced classes.
I am targeting this branch, because these changes breaks BC at some public method signatures.
```markdown
- Using deprecated `\Twig_` classes without namespace.
```
=> Use Twig namespaced classes

src/Provider/ImageProvider.php
The picture element does not render the correct media image description in the alt tag, getting double content for title and alt, this will result in double reading of the same text in screen readers and you will miss seo value
I am targeting this branch, because i made the PR BC by falling back onto the name.
```markdown
- the alt tag of media picture elements to the media description, falling back to the name when no description is present
```
=> Fix alt attribute not displaying the media's description in picture elements

src/Model/MediaInterface.php
We use Phpstan in our project, if we try to set the cdnFlushIdentifier with a string (which should be correct) phpstan is complaining about it being a boolean.
```markdown
- Changed parameter type in `MediaInterface::setCdnFlushIdentifier`
```
=> fix incorrect docblock

.travis.yml, .travis/before_install_test.sh, composer.json, src/Resizer/ImagineCompatibleResizerTrait.php, src/Resizer/SimpleResizer.php, src/Resizer/SquareResizer.php, tests/Resizer/ImagineCompatibleResizerTraitTest.php
Add possibility to use imagine >= 1.0.0
I am targeting this branch, because there should be no BC-break.
Closes #1605 
```markdown
- Imagine `^1.0` support
- SimpleResizer and SquareResizer resizers now use ImagineCompatibleResizerTrait
```
=> Add support for imagine ^1.0

src/Provider/FileProvider.php, src/Provider/FileProviderInterface.php
The `FileProvider` currently extends `BaseProvider`, but exposes additional methods in its public API beyond those from `MediaProviderInterface`, such as `getAllowedExtensions` and `getAllowedMimeTypes`, which are not part of any interface.
This hampers decoration as no interface provides these methods. Instead, one must either check for an instance of `FileProvider`, forcing you to extend rather than decorate, or use `method_exists`, which is suboptimal as well.
This extracts a new extending interface. 
This change should be backwards compatible with 3.x as only a new interface is added, but the contract for it was already implemented. Existing code targeting the `FileProvider` or extending it will remain operational.
Closes #1638.
```markdown
Extract and implement FileProviderInterface …
```
=> Extract FileProviderInterface from FileProvider

tests/Command/CleanMediaCommandTest.php, tests/Command/RemoveThumbsCommandTest.php, tests/Fixtures/FilesystemTestCase.php
The component archives have recently been modified so that they no longer
contain tests. We were relying on one of the fixtures that came with
thes tests. Copying the fixture to our project fixes the issue.
Allows using the component v 4.4
See https://github.com/symfony/filesystem/commit/f903e39aca6b4a4a2dbc473a1287b79b6c41cfb8#diff-fc723d30b02a4cca7a534518111c1a66
=> Steal Test fixture class from Filesystem component

src/Resources/config/gaufrette.xml
This bug was reporting when calling `lint:container`.
```markdown
- Add missing default service argument for `AmazonMetadataBuilder`
```
=> Add missing default service argument

composer.json, tests/Entity/GalleryManagerTest.php, tests/Entity/MediaManagerTest.php
It does not crash the test suite, which is a good quality to have.
=> Migrate to entity manager mock factory trait

src/DependencyInjection/Compiler/ThumbnailCompilerPass.php, tests/DependencyInjection/Compiler/ThumbnailCompilerPassTest.php
The ThumbnailCompilerPass add the "addResizer" method call on the thumbnail service
but this method is not on the ThumbnailInterface, so there is no guarantee it actually exists.
I do not take into account the fact that the service could be a child definition, as this is not the
case in "our" implementation. If someone alters it, it is his/her responsability.
I am targeting this branch, because it is a bug fix, backward compatible.
```markdown
Add the "addResizer" method call on the thumbnail service only if the method exists.
```
=> fix(thumbnail): add 'addResizer' method call only if the method exists

src/Controller/Api/GalleryController.php, src/Controller/Api/MediaController.php
This change the old string way to define types with the FQCN.
I am targeting this branch, because these changes are BC.
Closes #1655
```markdown
- Fixed using old string types to create forms
```
=> Use FQCN to create forms

composer.json
Allow "knplabs/gaufrette:0.9"
See https://github.com/KnpLabs/Gaufrette/blob/v0.9.0/CHANGELOG.md#v090.
```markdown
- Added support for "knplabs/gaufrette:0.9".
```
=> Allow "knplabs/gaufrette:0.9"

src/DependencyInjection/SonataMediaExtension.php
This PR fixes passing the default values to the `sonata.media.metadata.amazon` service. Since https://github.com/sonata-project/SonataMediaBundle/pull/1647, those defaults are passed as the second argument instead (making them useless). That regression prevent files from being publicly accessible by default in our case.
I am targeting this branch, because it fixes a bc break.
```markdown
- Fixed passing the default values to the `sonata.media.metadata.amazon` service.
```
I would appreciate a fast release ❤️
=> fix bc break: restore sonata.media.metadata.amazon service defaults

src/Command/AddMassMediaCommand.php, src/Command/AddMediaCommand.php, src/Command/CleanMediaCommand.php, src/Command/FixMediaContextCommand.php, src/Command/MigrateToJsonTypeCommand.php, src/Command/RefreshMetadataCommand.php, src/Command/RemoveThumbsCommand.php, src/Command/SyncThumbsCommand.php, src/Command/UpdateCdnStatusCommand.php
As of Symfony 4.4 (and required for 5.0) console commands should return integer as exit code *(`0` if  all gone ok)*
```markdown
Fixed deprecations
- `Return value of "Sonata\MediaBundle\Command\CleanMediaCommand::execute()" should always be of the type int since Symfony 4.4, NULL returned.`
- `Return value of "Sonata\MediaBundle\Command\FixMediaContextCommand::execute()" should always be of the type int since Symfony 4.4, NULL returned.`
- `Return value of "Sonata\MediaBundle\Command\RemoveThumbsCommand::execute()" should always be of the type int since Symfony 4.4, NULL returned.`
and others similar.
```
=> Console commands returning status code for Symfony4.4 and 5.0

src/Command/AddMassMediaCommand.php, src/Command/AddMediaCommand.php, src/Command/CleanMediaCommand.php, src/Command/FixMediaContextCommand.php, src/Command/MigrateToJsonTypeCommand.php, src/Command/RefreshMetadataCommand.php, src/Command/RemoveThumbsCommand.php, src/Command/SyncThumbsCommand.php, src/Command/UpdateCdnStatusCommand.php
PR https://github.com/sonata-project/SonataMediaBundle/pull/1679 fixes some deprecations as of Symfony 4.4 and required for Symfony 5.0, but breaks commands in `master` branch.
This PR fixes commands return types.
BC break as commands return types changes.
Completes https://github.com/sonata-project/SonataMediaBundle/pull/1679
```markdown
- Method `Sonata\MediaBundle\Command\AddMassMediaCommand::execute()` returns integer exit code
- Method `Sonata\MediaBundle\Command\AddMediaCommand::execute()` returns integer exit code
- Method `Sonata\MediaBundle\Command\CleanMediaCommand::execute()` returns integer exit code
- Method `Sonata\MediaBundle\Command\FixMediaContextCommand::execute()` returns integer exit code
- Method `Sonata\MediaBundle\Command\MigrateToJsonTypeCommand::execute()` returns …
```
=> [BC break] Fix commands return type

src/Generator/ODMGenerator.php, tests/Generator/ODMGeneratorTest.php
Class `Sonata\MediaBundle\Generator\ODMGenerator` can now be used *(instead of making a custom generator class)* in the case your domain is using VOs instead of UUID strings.
I am targeting this branch, because no BC breaks.
Closes https://github.com/sonata-project/SonataMediaBundle/issues/1681
```markdown
- Generating path when using VO representing UUID
```
=> Generate path when using VO as UUID representation

src/Resizer/SimpleResizer.php, tests/Resizer/SimpleResizerTest.php
Made width setting non-mandatory but made width or height setting mandatory on the resizer because there's no reason AFAIK to make one dimension mandatory, as long as there's one of them. See 
https://github.com/sonata-project/SonataMediaBundle/blob/315fe533dd4237243e6964efddaa314482970077/src/Resizer/SimpleResizer.php#L81-L83
I am targeting this branch, because this doesn't backwards compatible.
Closes #1571
```markdown
- Made width setting non-mandatory but made width or height setting mandatory on the resizer.
```
=> Made width setting non-mandatory

composer.json
Allow Twig 3.
```markdown
- Support for "twig/twig:^3.0".
=> Allow Twig 3

composer.json
Revert "Allow Twig 3".
This reverts commit 7c12b071c337e1e32eb407fb6e4785d1968ee782.
See https://github.com/sonata-project/SonataMediaBundle/pull/1717#issuecomment-602165154.
There is no need for changelog since the reverted commit is not released yet.
=> Revert "Allow Twig 3"

src/Command/CleanMediaCommand.php, src/Resources/config/command.xml, tests/Command/CleanMediaCommandTest.php
Fixes the command `sonata:media:clean-uploads`
> The "sonata.media.adapter.filesystem.local" service or alias has been removed or inlined when the container was compiled. You should either make it public, or stop using the contai
>   ner directly and use dependency injection instead.
Closes #1645
```markdown
- Removed all calls to container inside the CleanMediaCommand 
```
=> Fix command media:clean-uploads

src/Admin/GalleryAdmin.php
Without the change, `messages` would be used as default translation domain. This is wrong, because we always use `SonataMediaBundle` as domain when translating the context.
```markdown
- Fix missing translation of gallery context
```
=> Fix missing translation of gallery context

docs/reference/installation.rst
There is no mention in the docs fo the `media-orm-pack` and `media-odm-pack` flex recipes.
These are really practical and take care of the whole configuration automatically.
=> Document the media-orm-pack and media-odm-pack flex recipes

src/Model/NoDriverManager.php, tests/Model/NoDriverManagerTest.php
Closes https://github.com/sonata-project/SonataMediaBundle/issues/1721
```markdown
* Fix `bin/console lint:container` command and pass an object of class `NoDriverManager` of the expected `GalleryManagerInterface` interface
```
=> NoDriver should extend ManagerInterface to be able to be passed to `sonata.media.block.gallery_list` service

src/Provider/FileProvider.php
Adding max file size as a parameter, it will be easier to override the translation in your projects, now you will have to put 'The file is too big, max size: 256M':'your translation 256M', when using parameters it doesn't matter what the max file size is, This solution will modify the translation key with 'The file is too big, max size: %maxFileSize%':'your translation %maxFileSize%'.
```markdown
- adding maxFileSize as a parameter in the validation message
- Changed the validation message for the validation rule
```
=> Add max file size as a parameter in the validation message

composer.json, docs/reference/installation.rst, src/DependencyInjection/SonataMediaExtension.php, src/Resources/views/MediaAdmin/list_outer_rows_mosaic.html.twig, tests/DependencyInjection/SonataMediaExtensionTest.php
This bundle was using `truncate` filter without explicitly require `twig/extensions`, with this PR it uses `u` filter.
~I added `twig/extra-bundle` to autoload the Twig extension and a fallback in case Flex is not used.~
Ref: https://github.com/sonata-project/SonataAdminBundle/pull/6132
I am targeting this branch, because these changes are BC.
```markdown
- Added `twig/string-extra` dependency.
- Changed use of `truncate` filter with `u` filter.
```
=> Replace truncate filter with u filter

src/Model/NoDriverManager.php
Fixed booting up the kernel with missing driver:
```
Argument 3 passed to Sonata\MediaBundle\Command\CleanMediaCommand::__construct() must be an instance of Sonata\MediaBundle\Model\MediaManagerInterface, instance of Sonata\MediaBundle\Model\NoDriverManager given, called in /tmp/5ef3861662fc16.00020653/app-bundle/var/cache/ContainerIHVZ2OA/getCleanMediaCommandService.php on line 9       
```
```markdown
- Add missing `MediaManagerInterface` to `NoDriverManager`
```
=> Add missing interface to NoDriverManager

src/DependencyInjection/Compiler/TwigStringExtensionCompilerPass.php, src/DependencyInjection/SonataMediaExtension.php, src/SonataMediaBundle.php, tests/DependencyInjection/Compiler/AddProviderCompilerPassTest.php, tests/DependencyInjection/Compiler/ThumbnailCompilerPassTest.php, tests/DependencyInjection/Compiler/TwigStringExtensionCompilerPassTest.php, tests/DependencyInjection/SonataMediaExtensionTest.php
This PR contains:
- move StringExtension registration to Compiler pass and check all `twig.extension` service to avoid duplication
- improve tests
- fix previus broken checking
```php
... !is_a($container->getDefinition('twig.extension.string')->getClass(), StringExtension::class)) ...
// it is like this:   !is_a('Twig\Extra\String\StringExtension', StringExtension::class)) ...
```
I am targeting this branch, because this change respect BC.
PATCH for non release #1756.
=> Fix StringExtension registration

src/SonataMediaBundle.php, tests/App/Controller/TruncateController.php, tests/App/Resources/views/truncate_test.html.twig, tests/App/routes.yml, tests/Functional/Controller/TruncateControllerTest.php
This PR fix case when TwigStringExtensionCompilerPass is build after TwigEnvironmentPass - then u filter is not registred.
I am targeting this branch, because it is PATCH.
Changelog is not require. It is fix for non release PR #1758 and #1756.
=> Fix TwigStringExtensionCompilerPass priority

src/Resources/translations/SonataMediaBundle.fr.xliff
Add missing french translation for image_too_small error message #1743
This message added with #1743 is only present in `en` and `de` translation files but I'm only able to translate it in french.
=> Add french translation for image_too_small error message #1743

docs/reference/creating_a_provider_class.rst
I had an issue with my custom provider using the S3 filesystem.
The files were not publicly readable, which turned out to be because [this line](https://github.com/sonata-project/SonataMediaBundle/blob/3.x/src/Metadata/ProxyMetadataBuilder.php#L55) returned false and led to empty metadata.
This happened because my service was not public.
This updates the doc to a more modern yaml config and sets the service as public.
=> Update custom service provider configuration documentation

docs/reference/amazon_s3.rst, src/DependencyInjection/Configuration.php, src/DependencyInjection/SonataMediaExtension.php, tests/DependencyInjection/SonataMediaExtensionTest.php
Add endpoint configuration option for s3 filesystem.
Closes #1773 https://github.com/sonata-project/SonataMediaBundle/pull/1706
```markdown
- Added configuration option filesystem.s3.endpoint
```
=> endpoint configuration for s3 storage

src/Controller/Api/GalleryController.php, src/Controller/Api/MediaController.php
Update OpenAPI (Swagger) definition in order to be compatible with string identifiers (like UUIDs).
These changes are consistent with the API narrowing made at sonata-project/admin-bundle (see AdminInterface::id()).
Part of https://github.com/sonata-project/dev-kit/issues/778
Based on: https://github.com/sonata-project/SonataUserBundle/pull/1198
```markdown
- Removed requirements that were only allowing integers for model identifiers at Open API definitions.
- Fixed support for string model identifiers at Open API definitions.
```
=> Update Swagger definition in order to be compatible with string identifier

src/Controller/Api/GalleryController.php, tests/Controller/Api/GalleryControllerTest.php
Leverage `Collection::exists()` from `Gallery::getGalleryHasMedias()`.
I am targeting this branch, because this change is pedantic and respects BC.
=> Leverage `Collection::exists()` from `Gallery::getGalleryHasMedias()`

UPGRADE-3.x.md, composer.json, docs/reference/advanced_configuration.rst, docs/reference/amazon_s3.rst, src/CDN/CloudFront.php, src/DependencyInjection/Configuration.php, src/DependencyInjection/SonataMediaExtension.php, src/Resources/config/gaufrette.xml, src/Resources/config/media.xml, tests/App/config.yml, tests/CDN/CloudFrontTest.php, tests/DependencyInjection/SonataMediaExtensionTest.php, tests/Metadata/AmazonMetadataBuilderTest.php, tests/Metadata/ProxyMetadataBuilderTest.php
Fix support for "aws/aws-sdk-php:^3.0".
Related to #1018.
```markdown
- Fixed calls to deprecated method `AwsClient::factory()` when using aws/aws-sdk-php:^3.0;
- Fixed passing required arguments to "sonata.media.cdn.cloudfront" service when using aws/aws-sdk-php:^3.0;
- Fixed respecting "sonata_media.filesystem.s3.region", "sonata_media.filesystem.s3.version" and "sonata_media.filesystem.s3.endpoint" configuration nodes when using aws/aws-sdk-php:^2.0.
- Deprecated "sonata_media.filesystem.s3.sdk_version" configuration node.
```
=> Fix support for "aws/aws-sdk-php:^3.0"

src/Resources/config/routing/api/media.xml
I noticed that some of the routes in api/media.xml are not referencing the right controller. I am surprised that no-one noticed.
I am targeting this branch, because it is a backwards compatible fix.
```markdown
- Controller reference of some media API routes.
```
=> Fix controller references in media.xml

composer.json
Ref: https://github.com/sonata-project/dev-kit/issues/1069
We are dropping support for doctrine/mongodb-odm <2.0, this allows us to not install `alcaeus/mongo-php-adapter` in GA for tests.
I am targeting this branch, because these changes are BC.
```markdown
- Remove support for `doctrine/mongodb-odm` <2.0
```
=> Drop support for doctrine/mongodb-odm <2.0

docs/reference/extra.rst
Doc update : link for CoopTilleulsCKEditorSonataMediaBundle install doc was broken and unclickable.
=> Update link for CoopTilleulsCKEditorSonataMediaBundle install doc

UPGRADE-3.x.md, composer.json, docs/reference/advanced_configuration.rst, docs/reference/creating_a_provider_class.rst, docs/reference/installation.rst, src/Client/BuzzClient.php, src/DependencyInjection/Configuration.php, src/DependencyInjection/SonataMediaExtension.php, src/Metadata/AmazonMetadataBuilder.php, src/Provider/BaseVideoProvider.php, src/Provider/YouTubeProvider.php, src/Resources/config/provider.xml, tests/DependencyInjection/ConfigurationTest.php, tests/DependencyInjection/SonataMediaExtensionTest.php, tests/Metadata/AmazonMetadataBuilderTest.php, tests/Provider/AbstractProviderTest.php, tests/Provider/DailyMotionProviderTest.php, tests/Provider/VimeoProviderTest.php, tests/Provider/YouTubeProviderTest.php
I am targetting this branch, because this adds a new implementation without removing the existing one. This is a rework of https://github.com/sonata-project/SonataMediaBundle/pull/1181, but targets the psr http-client.
``` markdown
- Added support for `psr/http-client` in `BaseVideoProvider`
- Deprecate `Guzzle` and `Buzz` usage in `BaseVideoProvider`
```
Added support for an abstract http client without removing the existing old guzzle implementation.
=> Deprecate Guzzle with psr http-client

UPGRADE-3.x.md, src/DependencyInjection/Configuration.php, src/Resources/config/gaufrette.xml
Deprecate services related to `MogileFS` filesystem adapter, since it's [removed](https://github.com/KnpLabs/Gaufrette/blob/master/CHANGELOG.md#removed) in `knplabs/gaufrette:0.10.0`.
```markdown
- `sonata.media.adapter.filesystem.mogilefs` and `sonata.media.filesystem.mogilefs` services;
- `sonata_media.filesystem.mogilefs` configuration node.
```
=> Deprecate services related to `MogileFS` filesystem adapter

src/Validator/Constraints/ImageUploadDimensionValidator.php
I am targeting this branch because this is a bug fix.
Closes #1804 
```markdown
- Error on YouTube media creation in `ImageUploadDimensionValidator`
```
=> Fix error on YouTube media creation

src/Resources/translations/SonataMediaBundle.it.xliff
I am targeting this branch, because this is a minor improvement.
```markdown
- Missing translations
- `gallery` translation key into `Gallery`
```
=> Fix italian translations

docs/reference/command_line.rst, src/Command/UpdateCdnStatusCommand.php, src/Provider/BaseProvider.php, tests/Provider/BaseProviderTest.php
Fix CDN flush behavior.
The CDN flush behavior is an asynchronous operation. It consists in telling the CDN a path must be invalidated, in order to pick the path content again from its origin. This operation can take some time, so the invalidation result must be obtained using long polling, a scheduled task (like `UpdateCdnStatusCommand`) or something similar, in order to know if it has finished successfully or not. When this operation is done, the result is passed to `MediaInterface::setCdnStatus()`.
The users are able to mark a medium as flushable (indicating it must be track any update and kept fresh in the CDN) by calling `MediaInterface::setCdnIsFlushable()`.
Previous to this change, the behavior at `BaseProvider::flushCdn()` and `UpdateCdnStatusCommand` were making wrong assumptions …
=> Fix CDN flush behavior

UPGRADE-3.x.md, src/CDN/CDNInterface.php, src/CDN/CloudFront.php, src/CDN/CloudFrontVersion3.php, src/CDN/Server.php, src/DependencyInjection/SonataMediaExtension.php, src/Resources/config/media.xml, tests/CDN/CloudFrontClientSpy.php, tests/CDN/CloudFrontTest.php, tests/CDN/CloudFrontVersion3Test.php, tests/DependencyInjection/SonataMediaExtensionTest.php
Fix getting values returned by `CloudFrontClient` methods when using "aws/aws-sdk-php:^3.0".
The method `CloudFrontClient::getInvalidation()` from SDK [v2](https://docs.aws.amazon.com/aws-sdk-php/v2/api/class-Aws.CloudFront.CloudFrontClient.html#_getInvalidation) returns the following array structure:
```php
[
'Id' => '<string>',
'Status' => '<string>',
'CreateTime' => <DateTime>,
'InvalidationBatch' => [
'Paths' => [
'Items' => ['<string>', ...],
'Quantity' => <integer>,
],
'CallerReference' => '<string>',
],
'RequestId' => '<>',
]
```
while the SDK [v3](https://docs.aws.amazon.com/aws-sdk-php/v3/api/api-cloudfront-2018-06-18.html#getinvalidation) returns the following:
```php
[
'Invalidation' => [
'CreateTime' => <DateTime>,
'Id' => '<string>',
'InvalidationBatch' => [
'CallerReference' …
```
=> Fix getting values returned by `CloudFrontClient` methods when using "aws/aws-sdk-php:^3.0"

src/DependencyInjection/Compiler/ThumbnailCompilerPass.php
In PHP8, is_callable fails when checking for a non-static method with a classname. 
See https://github.com/php/php-src/blob/f5be0e5110ff816d2ce168c154cb3575d08e3cad/UPGRADING#L30
I haven't check other packages how have they solved this, maybe there is another way.
I guess the proper way to solve it (for next major version) is to create an interface with that method and check if the class implements that interface.
=> Replace is_callable call with ReflectionClass

src/Admin/GalleryAdmin.php, src/Resources/translations/SonataMediaBundle.de.xliff, src/Resources/translations/SonataMediaBundle.it.xliff
I am targeting this branch, because this is a small improvement.
```markdown
- Comments in `GalleryAdmin.php` for the next-major translations refactoring
- `SonataMediaBundle.de.xliff` re-arranged translation keys
- `SonataMediaBundle.it.xliff` fixed "gallery" and "Gallery" translations (case)
```
=> Small refactoring of translations files

src/Metadata/AmazonMetadataBuilder.php, tests/Metadata/AmazonMetadataBuilderTest.php
`AmazonMetadataBuilder->getContentType()` should not try to access the `$filename` parameter as a local file because it has been uploaded already to S3.
I am targeting this branch, because it's fixing a regression.
Closes #1854.
```markdown
- Guessing the content type of a file stored on Amazon S3.
```
=> Fix guessing mime type in AmazonMetadataBuilder

composer.json, src/Listener/PHPCR/MediaEventSubscriber.php, tests/Document/MediaManagerTest.php, tests/Entity/GalleryManagerTest.php, tests/Entity/MediaManagerTest.php, tests/PHPCR/MediaManagerTest.php
Since https://github.com/sonata-project/SonataNotificationBundle/releases/tag/3.11.0, we can use doctrine/persistence 2 in this bundle ; that's why tests are failing. I fixed this.
=> Add support for doctrine/persistence 2

UPGRADE-4.0.md, composer.json, src/Controller/Api/GalleryController.php, src/Controller/Api/MediaController.php, src/Document/GalleryManager.php, src/Document/MediaManager.php, src/Entity/GalleryManager.php, src/Entity/MediaManager.php, src/Model/GalleryManagerInterface.php, src/Model/MediaManagerInterface.php, src/Model/NoDriverManager.php, tests/Controller/Api/GalleryControllerTest.php, tests/Controller/Api/MediaControllerTest.php
I am targeting this branch, because this change provide BC-break.
```markdown
- Change using `Sonata\Doctrine\Model\PageableManagerInterface` in favor of `Sonata\DatagridBundle\Pager\PageableInterface`
- Removed support for `sonata-project/datagrid-bundle` < 3.0
```
=> Replace PageableManagerInterface in favor for PageableInterface

src/Document/GalleryManager.php, src/Document/MediaManager.php, src/PHPCR/GalleryManager.php, src/PHPCR/MediaManager.php
Replace some `\RuntimeException` exceptions with `\BadMethodCallException`.
I am targeting this branch, because these changes could break BC.
Related to https://github.com/sonata-project/SonataMediaBundle/pull/1925#discussion_r593355993.
```markdown
- Exceptions of type `\RuntimeException` to `\BadMethodCallException` thrown in these methods:
- `Sonata\MediaBundle\Document\GalleryManager::getPager()`;
- `Sonata\MediaBundle\Document\MediaManager::getPager()`;
- `Sonata\MediaBundle\PHPCR\GalleryManager::getPager()`;
- `Sonata\MediaBundle\PHPCR\MediaManager::getPager()`.
```
=> Replace some `\RuntimeException` exceptions with `\BadMethodCallException`

docs/reference/advanced_configuration.rst, docs/reference/installation.rst, src/DependencyInjection/SonataMediaExtension.php, src/Resizer/CropResizer.php, src/Resizer/ResizerInterface.php, src/Resources/config/media.xml, tests/Resizer/CropResizerTest.php
Adds a new resizer that is similar to the existing `SquareResizer`, but the result can have any image ratio.
The new resizer can crop the Image to a given ratio. When given an Image with 1200 x 700 and you want an image with the format 100 x 70, the resizer will first scale the image down to 120 x 70 and then crops the remaining parts down to 100 x 70.
I am targeting this branch, because this feature is BC.
```markdown
- Added `CropResizer`
```
=> Add CropResizer

src/Security/RolesDownloadStrategy.php, src/Security/SessionDownloadStrategy.php, tests/Security/SessionDownloadStrategyTest.php
Narrow some constructor type for `RolesDownloadStrategy` and `SessionSessionDownloadStrategy`.
Related to comments at #1923.
```markdown
- Stricter type checks for arguments at `RolesDownloadStrategy::__construct()`;
- Stricter type checks for arguments at `SessionDownloadStrategy::__construct()`.
```
=> Narrow some constructor types for `RolesDownloadStrategy` and `SessionDownloadStrategy`

composer.json
Declare conflict against nelmio/api-doc-bundle <2.13.5 || >=4.0.
Follow up of #1930.
```markdown
- Conflict against nelmio/api-doc-bundle <2.13.5 || >=4.0.
```
=> Declare conflict against nelmio/api-doc-bundle <2.13.5 || >=4.0

src/Security/ForbiddenDownloadStrategy.php, src/Security/PublicDownloadStrategy.php, src/Security/RolesDownloadStrategy.php, src/Security/SessionDownloadStrategy.php
Since release 3.31 I receive the following deprecation message:
> Passing other type than "Symfony\Contracts\Translation\TranslatorInterface" as argument 1 to "Sonata\MediaBundle\Security\RolesDownloadStrategy::__construct()" is deprecated since sonata-project/media-bundle 3.31 and will throw a "TypeError" error in 4.0.
This got introduced in PR #1923.
In my application, argument 1 is an instance of `Symfony\Component\Translation\DataCollectorTranslator`. This class implements both `TranslatorInterface`s, and I think this should not trigger the error.
I am targeting this branch, because it is backwards compatible.
```markdown
- Remove superfluous deprecation message when translator class is registered that implements both the legacy and new `TranslatorInterface`.
```
=> No deprecation message for classes that implement old and new TranslatorInterface

src/CDN/CloudFront.php, src/CDN/CloudFrontVersion3.php
Fix arguments passed to `sprintf()` in `flushPaths()` methods at `CloudFront` and `CloudFrontVersion3`.
I am targeting this branch, because {reason}.
```markdown
- Arguments passed to `sprintf()` in `flushPaths()` methods at `CloudFront` and `CloudFrontVersion3`.
```
=> Fix arguments passed to `sprintf()` in `flushPaths()` methods at `CloudFront` and `CloudFrontVersion3`

src/CDN/CloudFront.php, src/CDN/CloudFrontVersion3.php
Avoid to generate the same caller reference twice for a CloudFront invalidation batch request, since the CDN don't allow the submitted paths to be flushed if this reference was previously used.
See https://docs.aws.amazon.com/cloudfront/latest/APIReference/API_InvalidationBatch.html#cloudfront-Type-InvalidationBatch-CallerReference.
```markdown
- CDN invalidation from CloudFront when submitting paths that were previously invalidated.
```
=> Avoid to generate the same caller reference twice for a CloudFront invalidation batch request

UPGRADE-3.x.md, UPGRADE-4.0.md, src/Model/Gallery.php, src/Model/GalleryInterface.php, src/Model/GalleryItem.php, src/Model/GalleryItemInterface.php, src/Model/Media.php, src/Model/MediaInterface.php, tests/CDN/PantherPortalTest.php, tests/Entity/MediaTest.php, tests/Form/Type/MediaTypeTest.php, tests/Functional/Controller/TruncateControllerTest.php, tests/Provider/FileProviderTest.php
As detailed in related issue, this PR replace type hints and return type of DateTime with broader DateTimeInterface, allowing to use DateTimeImmutable.
I am targeting this branch, because change is BC.
Closes #1710
Replaced DateTime type hints and return types with DateTimeInterface 
```markdown
- Replaced DateTime type hints and return types with DateTimeInterface 
```
Added some checks in testing, to skip tests when not appliable.
Notice that this can be fixed in some other ways (e.g. by forcing some requires in dev). Anyway, I couldn't run my tests without such changes.
=> Datetimeinterface

src/Listener/BaseMediaEventSubscriber.php, src/Listener/ODM/MediaEventSubscriber.php, src/Listener/ORM/MediaEventSubscriber.php, tests/Listener/ORM/MediaEventSubscriberTest.php
When doing: https://github.com/sonata-project/SonataMediaBundle/pull/1975/files
I fucked up the event listeners. I didn't realize all entities go through this events, you just have to know if it is a media entity, otherwise do nothing.
Label it as pedantic since it wasn't released.
=> Fix event listeners

tests/Admin/BaseMediaAdminTest.php, tests/Admin/GalleryAdminTest.php, tests/Admin/GalleryItemAdminTest.php, tests/Admin/ORM/MediaAdminTest.php, tests/App/Provider/TestProvider.php, tests/Block/FeatureMediaBlockServiceTest.php, tests/Block/GalleryListBlockServiceTest.php, tests/Command/CleanMediaCommandTest.php, tests/Command/FixMediaContextCommandTest.php, tests/Command/RemoveThumbsCommandTest.php, tests/Controller/Api/GalleryTest.php, tests/Controller/GalleryAdminControllerTest.php, tests/Document/Media.php, tests/Document/MediaManagerTest.php, tests/Entity/Media.php, tests/Fixtures/FilesystemTestCase.php, tests/Form/Type/AbstractTypeTest.php, tests/Model/MediaTest.php, tests/Model/NoDriverManagerTest.php, tests/Provider/AbstractProviderTest.php, tests/Provider/FakeHttpWrapper.php
Adding typehints to tests to make it easy to bump phpstan on another PRs.
=> Add typehints to tests

src/Resources/config/controllers.php, src/Resources/config/doctrine_mongodb_admin.php, src/Resources/config/doctrine_orm_admin.php
This fix the missing MediaAdminController and GalleryAdminController service declarations.
I am targeting this branch, because only applicable on master branch.
=> Add missing service declaration

src/Resources/config/providers.php
Needed because of the InlineValidator in form-extension repo (See https://github.com/sonata-project/form-extensions/blob/master/src/Validator/InlineValidator.php#L53).
I am targeting this branch, because only applicable on master.
=> Set sonata.media.pool service as public

src/Provider/Pool.php
Closes #2014 .
```markdown
- Deprecate `getContext()` from Pool without first having that context.
```
=> Deprecate calling `getContext()` without existing context

src/Block/GalleryListBlockService.php, src/Resources/views/Block/block_gallery_list.html.twig, tests/Block/GalleryListBlockServiceTest.php
I am targeting this branch, because this breaks BC.
=> Avoid using pager if not needed

src/Block/FeatureMediaBlockService.php, src/Block/GalleryBlockService.php, src/Block/GalleryListBlockService.php, tests/Block/FeatureMediaBlockServiceTest.php, tests/Block/GalleryBlockServiceTest.php, tests/Block/GalleryListBlockServiceTest.php
Closes #1962 .
```markdown
- Added name for blocks so they can be recognized on SonataPageBundle.
```
=> Add getName on blocks for SonataPageBundle

UPGRADE-3.x.md, src/Resources/config/security.xml, src/Security/SessionDownloadStrategy.php, tests/Security/SessionDownloadStrategyTest.php
```markdown
- Direct injection of `SessionInterface` on `SessionDownloadStrategy`, we use `RequestStack` to avoid deprecations.
```
=> Inject requestStack instead of SessionInterface to avoid deprecation

src/Extra/Pixlr.php
Backporting directly from master branch.
Closes #1670 .
```markdown
- Fixed adding new Media with Pixlr enabled.
```
=> Fix pixlr not able to handle nullable extension

UPGRADE-3.x.md, src/Filesystem/Replicate.php
Deprecate unused argument 3 in `Replicate::write()`.
```markdown
- Unused argument 3 in `Replicate::write()`.
```
=> Deprecate unused argument 3 in `Replicate::write()`

src/Client/BuzzClient.php
Fix support for "kriswallsmith/buzz" <0.16.
Function `Browser::sendRequest()` was introduced in "kriswallsmith/buzz" ^0.16, but we are using it relying it's always available:
https://github.com/sonata-project/SonataMediaBundle/blob/08bf82969673cd78e166a6c81408716c5587f7a1/src/Client/BuzzClient.php#L40
See https://github.com/kriswallsmith/Buzz/blob/master/CHANGELOG.md#added-6.
```markdown
- Call to undefined function `Buzz\Browser::sendRequest()` with "kriswallsmith/buzz" <0.16.
```
=> Fix support for "kriswallsmith/buzz" <0.16

src/Resources/translations/SonataMediaBundle.bg.xliff, src/Resources/translations/SonataMediaBundle.ca.xliff, src/Resources/translations/SonataMediaBundle.cs.xliff, src/Resources/translations/SonataMediaBundle.de.xliff, src/Resources/translations/SonataMediaBundle.en.xliff, src/Resources/translations/SonataMediaBundle.es.xliff, src/Resources/translations/SonataMediaBundle.fa.xliff, src/Resources/translations/SonataMediaBundle.fi.xliff, src/Resources/translations/SonataMediaBundle.fr.xliff, src/Resources/translations/SonataMediaBundle.hu.xliff, src/Resources/translations/SonataMediaBundle.ja.xliff, src/Resources/translations/SonataMediaBundle.lt.xliff, src/Resources/translations/SonataMediaBundle.nl.xliff, src/Resources/translations/SonataMediaBundle.pl.xliff, src/Resources/translations/SonataMediaBundle.pt_BR.xliff, src/Resources/translations/SonataMediaBundle.ro.xliff, src/Resources/translations/SonataMediaBundle.uk.xliff
I am targeting this branch, because the placeholders are fake translations.
Part of https://github.com/sonata-project/dev-kit/issues/1614
=> Remove placeholders from translations

src/Model/GalleryInterface.php, src/Model/Media.php, src/Model/MediaInterface.php, src/Provider/BaseVideoProvider.php, src/Provider/MediaProviderInterface.php, tests/Fixtures/SonataClassificationBundle/Model/CategoryInterface.php, tests/Fixtures/SonataClassificationBundle/Model/ContextInterface.php
Add missing methods to interfaces and abstract classes.
Part of #2035.
```markdown
- Missing method declarations in interfaces and abstract classes, through `@method` annotation in order to respect BC.
```
=> Add missing methods to interfaces and abstract classes

UPGRADE-3.x.md, src/Listener/BaseMediaEventSubscriber.php, src/Listener/ODM/MediaEventSubscriber.php, src/Listener/ORM/MediaEventSubscriber.php, src/Listener/PHPCR/MediaEventSubscriber.php, src/Provider/FileProvider.php, tests/Listener/ORM/MediaEventSubscriberTest.php
Fix some return types.
I am targeting this branch, because these changes try to respect BC.
See #1991.
```markdown
- Return type at `BaseMediaEventSubscriber::getProvider()`.
- Return `null` from `BaseMediaEventSubscriber::getMedia()` if the related media does not implement `MediaInterface`.
```
=> Fix some return types

src/Metadata/ProxyMetadataBuilder.php, src/Resources/config/gaufrette.php, tests/DependencyInjection/SonataMediaExtensionTest.php, tests/Metadata/ProxyMetadataBuilderTest.php
I am targeting this branch, because this is BC break.
```markdown
- Avoid using container on `ProxyMetadataBuilder`, instead use the media pool.
```
=> Avoid using container on ProxyMetadataBuilder

src/Form/Type/MediaType.php
I am targeting this branch, because this is bugfixing.
Closes #2100 .
```markdown
- Fixed missing upload after submit of MediaType field.
```
Same fix applied for master but the bug was backported to 3.x so the fix applies for 3.x too, in this case it was released so changelog is needed.
=> Fix upload of media through MediaType

UPGRADE-3.x.md, src/Block/Breadcrumb/BaseGalleryBreadcrumbBlockService.php, src/Block/Breadcrumb/GalleryIndexBreadcrumbBlockService.php, src/Block/Breadcrumb/GalleryViewBreadcrumbBlockService.php, src/Block/Breadcrumb/MediaViewBreadcrumbBlockService.php, src/Controller/GalleryController.php, src/Controller/MediaController.php, tests/Controller/MediaControllerTest.php
We should deprecate those methods because they do not provide any value and they can be easily implement in case someone needs to show a media detail and list of galleries.
Breadcrumb were directly related to those actions. Again , if someone need those actions for the frontend of his app. He might need or not the breadcrumbs.
```markdown
- Deprecate controller actions for showing media and galleries.
- Deprecate breadcrumb classes.
```
=> Deprecate index and view controller method

UPGRADE-3.x.md, src/DependencyInjection/Configuration.php, src/Extra/Pixlr.php, src/Resources/views/Extra/pixlr_editor.html.twig, src/Resources/views/Extra/pixlr_exit.html.twig, src/Twig/GlobalVariables.php
Closes #2107 .
Closes #1092 .
```markdown
- Deprecated Pixlr integration.
```
=> Deprecate Pixlr integration

src/Resources/config/routing/media.xml
I am targeting this branch, because this is hotfix for master.
On 3.x this is not a problem because controller are not registered as a service.
=> Fix media route for download action

src/Controller/GalleryAdminController.php, src/Controller/MediaAdminController.php, src/Filesystem/Replicate.php, src/Form/DataTransformer/ProviderDataTransformer.php, src/Form/DataTransformer/ServiceProviderDataTransformer.php, src/Form/Type/ApiMediaType.php, src/Form/Type/MediaType.php, src/Listener/ODM/MediaEventSubscriber.php, src/Listener/ORM/MediaEventSubscriber.php, src/Twig/TokenParser/MediaTokenParser.php, src/Twig/TokenParser/PathTokenParser.php, src/Twig/TokenParser/ThumbnailTokenParser.php, src/Validator/Constraints/ValidMediaFormat.php, tests/App/AppKernel.php, tests/Filesystem/ReplicateTest.php, tests/Provider/DailyMotionProviderTest.php, tests/Provider/VimeoProviderTest.php, tests/Provider/YouTubeProviderTest.php
I am targeting this branch, because this is BC break on 3.x.
```markdown
- Deprecations shown on Symfony 5.4
```
=> Fix deprecations from Symfony 5.4 typing system

UPGRADE-3.x.md, src/Controller/Api/GalleryController.php, src/Controller/Api/MediaController.php, src/DependencyInjection/SonataMediaExtension.php, src/Document/GalleryManager.php, src/Document/MediaManager.php, src/Entity/GalleryManager.php, src/Entity/MediaManager.php, src/Extra/ApiMediaFile.php, src/Form/Type/ApiDoctrineMediaType.php, src/Form/Type/ApiGalleryHasMediaType.php, src/Form/Type/ApiGalleryType.php, src/Form/Type/ApiMediaType.php, src/Model/GalleryManagerInterface.php, src/Model/MediaManagerInterface.php, src/Serializer/GallerySerializerHandler.php, src/Serializer/MediaSerializerHandler.php, tests/Controller/Api/GalleryControllerTest.php, tests/Controller/Api/MediaControllerTest.php, tests/Entity/GalleryManagerTest.php, tests/Entity/MediaManagerTest.php
```markdown
- Deprecated ReST API with FOSRest, Nelmio Api Docs and JMS Serializer.
```
=> [RFC] Deprecate ReST API
