- Provider/FileProvider.php
> Fix issue on file provider postUpdate callback

- Resources/translations/SonataMediaBundle.fa.xliff
> adding SonataMediaBundle.fr.xliff language file

- Controller/Api/GalleryController.php
- Controller/Api/MediaController.php
- Document/GalleryManager.php
- Document/MediaManager.php
- Entity/GalleryManager.php
- Entity/MediaManager.php
- Model/GalleryManagerInterface.php
- Model/MediaManagerInterface.php
- PHPCR/GalleryManager.php
- PHPCR/MediaManager.php
- Tests/Controller/Api/GalleryControllerTest.php
- Tests/Controller/Api/MediaControllerTest.php
- Tests/Entity/GalleryManagerTest.php
- Tests/Entity/MediaManagerTest.php
Implement API pagination through PageableManagerInterface with unit testing
(Method 'getPager' throw an exception 'Not Implemented yet' in ODM and PHPCR managers)
>  Implement pagination to Gallery API and Media API

- Controller/Api/MediaController.php
- Extra/ApiMediaFile.php
- Form/DataTransformer/ProviderDataTransformer.php
- Model/MediaInterface.php
- Provider/FileProvider.php
- Provider/ImageProvider.php
- Tests/Controller/Api/MediaControllerTest.php
- Tests/Form/DataTransformer/ProviderDataTransformerTest.php
- Tests/Provider/FileProviderTest.php
- Tests/Provider/phpSapiNameOverride.php
Add route in api to update a media binary content
> Media binary

- Controller/GalleryAdminController.php
- Controller/MediaAdminController.php
fixed declarations because of the following commit:
https://github.com/sonata-project/SonataAdminBundle/commit/daaf7e980db2d26f305e9ce7c04084da560539fd
> getRequest() and the request service are deprecated

- Provider/FileProvider.php
Right now there is now way to translate this message in validators.[lang].xliff
> Updated FileProvider.php for translation

- Resources/doc/reference/advanced_configuration.rst
Update doc to add "class" line when working with custom classification entity "category"
> [Doc] Update advanced configuration

- CHANGELOG.md
- Provider/BaseProvider.php
* Ensure object exists in FS in ```BaseProvider::flushCdn()```
* Updated docblock for ```BaseProvider::flushCdn()```
* Updated ```CHANGELOG.md``` with BC break from ```CDNInterface```
> Updated BaseProvider.php, CHANGELOG.md

- .travis.yml
Should fix: https://travis-ci.org/sonata-project/SonataMediaBundle/jobs/66390237#L108
> Unset memory limit on Travis

- Form/Type/ApiMediaType.php
- Form/Type/MediaType.php
> Fix deprecated FormType::setDefaultOptions usage

- CHANGELOG.md
- composer.json
> Bump jms/serializer-bundle requirement to include ~1.0

- Form/Type/MediaType.php
| Q             | A
| ------------- | ---
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets |
| License       | MIT
| Doc PR        |
> Replaced deprecated "BIND" form event

- Resources/translations/SonataMediaBundle.de.xliff
Added some missing translation keys
> German translation

- Resizer/SimpleResizer.php
and overwrite just this method
> now it is possible to extend the simple resizer

- Resources/translations/SonataMediaBundle.de.xliff
- Resources/views/Form/media_widgets.html.twig
Fixes #838
before:
after:
i added some translation keys, when this PR is ready to merge, i will updated the other translation files
> finetuning the media widget

- Resources/translations/SonataMediaBundle.bg.xliff
- Resources/translations/SonataMediaBundle.de.xliff
- Resources/translations/SonataMediaBundle.en.xliff
- Resources/translations/SonataMediaBundle.es.xliff
- Resources/translations/SonataMediaBundle.fa.xliff
- Resources/translations/SonataMediaBundle.fi.xliff
- Resources/translations/SonataMediaBundle.fr.xliff
- Resources/translations/SonataMediaBundle.hu.xliff
- Resources/translations/SonataMediaBundle.it.xliff
- Resources/translations/SonataMediaBundle.ja.xliff
- Resources/translations/SonataMediaBundle.lt.xliff
- Resources/translations/SonataMediaBundle.nl.xliff
- Resources/translations/SonataMediaBundle.pl.xliff
- Resources/translations/SonataMediaBundle.pt_BR.xliff
- Resources/translations/SonataMediaBundle.ro.xliff
- Resources/translations/SonataMediaBundle.ru.xliff
- Resources/translations/SonataMediaBundle.sl.xliff
- Resources/translations/SonataMediaBundle.uk.xliff
- Resources/views/Form/media_widgets.html.twig
> updated translation file for media widget

- DependencyInjection/SonataMediaExtension.php
- Metadata/ProxyMetadataBuilder.php
Ported the fixed ACL submission for AWS to 2.3 branch
> Fixed ACL submission for AWS

- Provider/FileProvider.php
Refs #838
you can finde more information about this PR here: 
https://github.com/sonata-project/SonataMediaBundle/issues/838#issuecomment-137134101
> the binary content is not required in the media widget

- Resources/config/doctrine/Media.phpcr.xml.skeleton
The namespace is ...\Document\... instead of ..\PHPCR\...
> Fix namespace in Media.phpcr.xml.skeleton

- Resources/doc/reference/extra.rst
> minor documentation rst link format fix

- Controller/Api/GalleryController.php
- Controller/Api/MediaController.php
> added missing use statements. refs #876

- Controller/Api/MediaController.php
fixes https://github.com/sonata-project/SonataMediaBundle/issues/876
> AnnotationException fix, refs. https://github.com/sonata-project/SonataMediaBundle/issues/876

- Model/MediaInterface.php
Used here https://github.com/sonata-project/SonataMediaBundle/blob/master/Model/MediaInterface.php#L362-L365
> Missing import in MediaInterface

- Filesystem/Replicate.php
- Model/GalleryInterface.php
- Model/MediaInterface.php
- Provider/BaseProvider.php
- Provider/MediaProviderInterface.php
Found some more places where we could use a better phpdoc.
> Fixed phpdoc

- PHPCR/BaseGalleryHasMediaRepository.php
- PHPCR/BaseGalleryRepository.php
- PHPCR/BaseMediaRepository.php
Hello,
I changed class names of the PHPCR repositories to be PSR compatible. I was unable to autoload them via composer.
Please, if you accept it, let me know when it will be available as a release.
Thank you,
Regards,
Peekmo
> (PHPCR) Fix PSR naming of PHPCR repositories

- Form/Type/MediaType.php
- Provider/BaseVideoProvider.php
- Provider/FileProvider.php
- Resources/translations/SonataMediaBundle.bg.xliff
- Resources/translations/SonataMediaBundle.de.xliff
- Resources/translations/SonataMediaBundle.en.xliff
- Resources/translations/SonataMediaBundle.es.xliff
- Resources/translations/SonataMediaBundle.fa.xliff
- Resources/translations/SonataMediaBundle.fi.xliff
- Resources/translations/SonataMediaBundle.fr.xliff
- Resources/translations/SonataMediaBundle.hu.xliff
- Resources/translations/SonataMediaBundle.it.xliff
- Resources/translations/SonataMediaBundle.ja.xliff
- Resources/translations/SonataMediaBundle.lt.xliff
- Resources/translations/SonataMediaBundle.nl.xliff
- Resources/translations/SonataMediaBundle.pl.xliff
- Resources/translations/SonataMediaBundle.pt_BR.xliff
- Resources/translations/SonataMediaBundle.ro.xliff
- Resources/translations/SonataMediaBundle.ru.xliff
- Resources/translations/SonataMediaBundle.sl.xliff
- Resources/translations/SonataMediaBundle.uk.xliff
Fixed https://github.com/sonata-project/SonataMediaBundle/issues/888
Before
After
Translations
> Translate media widget

- Block/FeatureMediaBlockService.php
- Block/GalleryBlockService.php
- Block/MediaBlockService.php
- Resources/translations/SonataMediaBundle.bg.xliff
- Resources/translations/SonataMediaBundle.de.xliff
- Resources/translations/SonataMediaBundle.en.xliff
- Resources/translations/SonataMediaBundle.es.xliff
- Resources/translations/SonataMediaBundle.fa.xliff
- Resources/translations/SonataMediaBundle.fi.xliff
- Resources/translations/SonataMediaBundle.fr.xliff
- Resources/translations/SonataMediaBundle.hu.xliff
- Resources/translations/SonataMediaBundle.it.xliff
- Resources/translations/SonataMediaBundle.ja.xliff
- Resources/translations/SonataMediaBundle.lt.xliff
- Resources/translations/SonataMediaBundle.nl.xliff
- Resources/translations/SonataMediaBundle.pl.xliff
- Resources/translations/SonataMediaBundle.pt_BR.xliff
- Resources/translations/SonataMediaBundle.ro.xliff
- Resources/translations/SonataMediaBundle.ru.xliff
- Resources/translations/SonataMediaBundle.sl.xliff
- Resources/translations/SonataMediaBundle.uk.xliff
> Translate block labels

- Block/GalleryListBlockService.php
- Resources/config/block.xml
- Resources/translations/SonataMediaBundle.bg.xliff
- Resources/translations/SonataMediaBundle.de.xliff
- Resources/translations/SonataMediaBundle.en.xliff
- Resources/translations/SonataMediaBundle.es.xliff
- Resources/translations/SonataMediaBundle.fa.xliff
- Resources/translations/SonataMediaBundle.fi.xliff
- Resources/translations/SonataMediaBundle.fr.xliff
- Resources/translations/SonataMediaBundle.hu.xliff
- Resources/translations/SonataMediaBundle.it.xliff
- Resources/translations/SonataMediaBundle.ja.xliff
- Resources/translations/SonataMediaBundle.lt.xliff
- Resources/translations/SonataMediaBundle.nl.xliff
- Resources/translations/SonataMediaBundle.pl.xliff
- Resources/translations/SonataMediaBundle.pt_BR.xliff
- Resources/translations/SonataMediaBundle.ro.xliff
- Resources/translations/SonataMediaBundle.ru.xliff
- Resources/translations/SonataMediaBundle.sl.xliff
- Resources/translations/SonataMediaBundle.uk.xliff
- Resources/views/Block/block_gallery_list.html.twig
- Tests/Block/GalleryListBlockServiceTest.php
> Added gallery list block

- Tests/Provider/ImageProviderTest.php
- Thumbnail/FormatThumbnail.php
> Backport PR #846 to master

- .travis.yml
The mongo extension was missing.
> Fixed build

- Resources/doc/reference/advanced_configuration.rst
- Resources/doc/reference/api.rst
- Resources/doc/reference/creating_a_provider_class.rst
- Resources/doc/reference/form.rst
- Resources/doc/reference/installation.rst
- Resources/doc/reference/troubleshooting.rst
> Fix broken build

- Model/Media.php
> PHPDoc fix

- Provider/YouTubeProvider.php
- Tests/Provider/YouTubeProviderTest.php
The regex wasn't accepting mobile youtube videos.
> Possibility to create youtube videos Media from mobile

- Tests/Command/FixMediaContextCommandTest.php
Old versions of symfony do not add it automatically.
> specify command name

- Admin/GalleryAdmin.php
- Resources/views/GalleryAdmin/list.html.twig
> UI: Updated GalleryAdmin context picker

- Command/CleanMediaCommand.php
- Tests/Command/CleanMediaCommandTest.php
This command scans the upload directory and removes unlinked files.
> Created new command for cleaning upload directory

- DependencyInjection/Compiler/SecurityContextCompilerPass.php
- Tests/Security/RolesDownloadStrategyTest.php
- Tests/Validator/FormatValidatorTest.php
This is a PR of the outmost importance merge ASAP plz
> spell the name of our framework right

- DependencyInjection/Compiler/AddProviderCompilerPass.php
- DependencyInjection/Configuration.php
- DependencyInjection/SonataMediaExtension.php
- Resources/doc/reference/advanced_configuration.rst
- Tests/DependencyInjection/ConfigurationTest.php
The settings for the admin thumbnail should be configurable.
> Admin thumbnail format configuration

- Provider/VimeoProvider.php
- Resources/views/Provider/view_vimeo.html.twig
As seen in other providers, providing class attribute for a twig helper (and also some Vimeo iframe attributes)
> Added class and fullscreen attributes for the Vimeo helper

- composer.json
**THIS BUNDLE WILL HAVE A NEW MAJOR RELEASE**
* 3.x-dev
* Use new composer constraints notation
* Remove minimum-stability option to clearly show which required packages are not stable
> Composer fixes and improvements

- Tests/Command/CleanMediaCommandTest.php
Closes N/A (Not passing tests)
```markdown
- Added `Sonata\MediaBundle\Tests\Command\CleanMediaCommandTest::assertOutputFoundInContext` to check for multiple lines of the output of the command within a context
- Failing tests `testExecuteFilesExistsVerbose`, `testExecute` and `testExecuteDryRun`
```
While rebasing #1017, I noticed only a few kind of tests were failing. I took the occasion to fix them.
> Fix CleanMediaCommandTest

- Resources/doc/reference/extra.rst
Rebase of #986
A wrong format type and indention was used.
> Fixed correct code example format in extra.rst

- Controller/MediaAdminController.php
Replaces #997
Refs #996 
Variable name should be category regarding to return
> variable name should be category regarding to return

- CDN/CloudFront.php
- Tests/CDN/CloudFrontTest.php
Closes #
```markdown
- Changed `CloudFrontClient::setClient` signature to accept only `CloudFrontClient`
```
Removed deprecation on `CloudFrontClient::setClient` method
> Added CloudFrontClient type hint

- Resources/config/security.xml
- Resources/doc/reference/security.rst
- Resources/translations/SonataMediaBundle.bg.xliff
- Resources/translations/SonataMediaBundle.de.xliff
- Resources/translations/SonataMediaBundle.en.xliff
- Resources/translations/SonataMediaBundle.es.xliff
- Resources/translations/SonataMediaBundle.fa.xliff
- Resources/translations/SonataMediaBundle.fi.xliff
- Resources/translations/SonataMediaBundle.fr.xliff
- Resources/translations/SonataMediaBundle.hu.xliff
- Resources/translations/SonataMediaBundle.it.xliff
- Resources/translations/SonataMediaBundle.ja.xliff
- Resources/translations/SonataMediaBundle.lt.xliff
- Resources/translations/SonataMediaBundle.nl.xliff
- Resources/translations/SonataMediaBundle.pl.xliff
- Resources/translations/SonataMediaBundle.pt_BR.xliff
- Resources/translations/SonataMediaBundle.ro.xliff
- Resources/translations/SonataMediaBundle.ru.xliff
- Resources/translations/SonataMediaBundle.sl.xliff
- Resources/translations/SonataMediaBundle.uk.xliff
- Security/SessionDownloadStrategy.php
- Tests/Security/SessionDownloadStrategyTest.php
Refs #1033
```markdown
- Added test for `Security/SessionDownloadStrategy`
- `$container` property in `Security/SessionDownloadStrategy`
- Injection of `Session` instead of the whole `Container` in `Security/SessionDownloadStrategy`
```
See #1032 and #1033
> Changed injection of container to session, added deprecated to container and added test

- composer.json
Closes #
```markdown
- Added some `Class::newMethod` to do great stuff
```
> Fix typo on tilleuls/ckeditor-sonata-media-bundle suggestion

- Security/SessionDownloadStrategy.php
- Tests/Security/SessionDownloadStrategyTest.php
Replaces #1032 and #1015
```markdown
- Injection of `session` instead of the whole `container` in `Security/SessionDownloadStrategy`
```
> Changed injection of container in SessionDownloadStrategy and added test

- composer.json
Support for latest dev branch of `sonata-project/classification-bundle`.
> Support dev version of classification-bundle

- Model/GalleryHasMediaInterface.php
- Model/GalleryInterface.php
- Tests/Controller/Api/GalleryControllerTest.php
- UPGRADE-4.0.md
```markdown
- Added missing `GalleryHasMediaInterface::getId` method
- Added missing `GalleryInterface::getId` method
```
Added missing id getters to model classes
> Added missing id getters

- Resources/doc/reference/installation.rst
Refs #1012
See comment: https://github.com/sonata-project/SonataMediaBundle/pull/1012/files#r66574910
> simplify composer command in docs

- Controller/Api/GalleryController.php
- Controller/Api/MediaController.php
- Tests/Controller/Api/GalleryControllerTest.php
- composer.json
```markdown
- Support for FOSRestBundle 2.0
```
Some methods were removed or changed in the 2.0 version.
> Support for FOSRestBundle 2.0

- CHANGELOG.md
- Command/AddMediaCommand.php
- Controller/Api/GalleryController.php
- Controller/Api/MediaController.php
- DependencyInjection/SonataMediaExtension.php
- Form/Type/ApiMediaType.php
- Form/Type/MediaType.php
- Provider/BaseVideoProvider.php
- Provider/FileProvider.php
- Provider/Pool.php
- Tests/Block/GalleryListBlockServiceTest.php
- Tests/Controller/Api/GalleryControllerTest.php
- Tests/Form/Type/AbstractTypeTest.php
- Tests/Form/Type/ApiMediaTypeTest.php
- Tests/Form/Type/MediaTypeTest.php
- Tests/Metadata/ProxyMetadataBuilderTest.php
- Tests/Provider/AbstractProviderTest.php
- Tests/Provider/BaseProviderTest.php
- Tests/Provider/DailyMotionProviderTest.php
- Tests/Provider/FileProviderTest.php
- Tests/Provider/ImageProviderTest.php
- Tests/Provider/VimeoProviderTest.php
- Tests/Provider/YouTubeProviderTest.php
- UPGRADE-3.x.md
- composer.json
> Merge 3.x into master

- composer.json
```markdown
- Allow `knplabs/gaufrette` `^0.2`
```
> Updated knplabs/gaufrette dependency

- Provider/Pool.php
Fixes #1090
```markdown
- Fixed loop in Pool::getDownloadSecurity
```
https://github.com/sonata-project/SonataMediaBundle/pull/1014 introduced a loop
> Fixed loop in Pool::getDownloadSecurity

- Controller/MediaAdminController.php
Fix second problem from #1111 
```markdown
- Use `$request` instead of  `$this->get('request')`
```
Fix problem in create media page [admin]
> Fix problem with non-existent service "request"

- Resources/translations/SonataMediaBundle.sl.xliff
I am targetting this branch, because it updates Slovenian translation (sl_SI)
This is a minor patch that updates Slovenian translation (sl_SI).
> Update sl_SI translation

- Consumer/CreateThumbnailConsumer.php
I am targetting this branch, because this is BC
Formatted exception messages
> formatted exception messages

- Resources/translations/SonataMediaBundle.it.xliff
Fix italian translation, add some missing translations and make existing one consistent with other sonata bundles.
> Fix italian translations

- Provider/FileProvider.php
- Tests/Provider/FileProviderTest.php
Rebase of #601 
Fixes #593 #600 #360
``` markdown
- Added filesize check to upload
- Added empty filename check to upload
```
Added some checks while uploading a file.
> Added upload checks

- Block/FeatureMediaBlockService.php
- Block/GalleryBlockService.php
- Block/MediaBlockService.php
- Controller/Api/GalleryController.php
- Controller/Api/MediaController.php
- DependencyInjection/SonataMediaExtension.php
- Form/Type/ApiMediaType.php
- Security/SessionDownloadStrategy.php
- Tests/Controller/Api/GalleryControllerTest.php
- Tests/Controller/Api/MediaControllerTest.php
- Tests/Entity/GalleryManagerTest.php
- Tests/Entity/MediaManagerTest.php
- Tests/Form/Type/ApiMediaTypeTest.php
- Tests/Security/SessionDownloadStrategyTest.php
- Tests/Twig/Extension/MediaExtensionTest.php
I am targetting this branch, because is BC and only a PHP Doc fix.
> fixed PHPDoc author

- Command/AddMediaCommand.php
- Metadata/ProxyMetadataBuilder.php
- Thumbnail/ConsumerThumbnail.php
- UPGRADE-3.x.md
Refs #1124
- Fixed the wrong deprecation message, which was introduced here: https://github.com/sonata-project/SonataMediaBundle/pull/1124#discussion_r97044541 and added an UPGRADE note
- added to two more deprecations in separate commits
> fixed deprecation msg and added an UPGRADE note

- Provider/Pool.php
I am targetting this branch, because is BC.
> avoid long line

- Controller/GalleryAdminController.php
- Controller/MediaAdminController.php
- Tests/Controller/GalleryAdminControllerTest.php
- Tests/Controller/MediaAdminControllerTest.php
Same changes applied on MediaAdminController here https://github.com/sonata-project/SonataMediaBundle/pull/1196, but applied to GalleryAdminController.
> Refactor on GalleryAdminController

- Admin/GalleryHasMediaAdmin.php
- phpunit.xml.dist
I am targeting this branch, because this is pedantic.
I think coverage is not calculated correctly, lets see
> Remove exceptions from phpunit whitelist

- Tests/DependencyInjection/SonataMediaExtensionTest.php
- composer.json
I am targeting this branch, because this is a refactoring.
```markdown
- DI tests now use SymfonyDependencyInjectionTest
```
> DI test refactoring

- .gitattributes
- .github/ISSUE_TEMPLATE.md
- .styleci.yml
- .travis.yml
- .travis/before_install_test.sh
- .travis/install_test.sh
- CONTRIBUTING.md
- composer.json
```markdown
- Rollback to PHP 5.6 as minimum support.
```
> DevKit updates for 3.x branch

- src/Command/RefreshMetadataCommand.php
- src/Command/UpdateCdnStatusCommand.php
```markdown
- Sf3 compatibility on the refresh-metadata and update-cdn-status commands (dialog helper)
```
Calls of DialogHelper replaced with calls to QuestionHelper
> Sf3 compatibility fix for refresh-metadata and update-cdn-status commands

- tests/Admin/BaseMediaAdminTest.php
> Mock new call

- .php_cs.dist
- .travis.yml
- .travis/before_install_test.sh
- .travis/check_relevant_lint.sh
- .travis/install_test.sh
- src/Admin/BaseMediaAdmin.php
- src/Admin/GalleryAdmin.php
- src/Admin/GalleryItemAdmin.php
- src/Admin/ORM/MediaAdmin.php
- src/Block/FeatureMediaBlockService.php
- src/Block/GalleryBlockService.php
- src/Block/GalleryListBlockService.php
- src/Block/MediaBlockService.php
- src/Form/DataTransformer/ProviderDataTransformer.php
- src/Form/DataTransformer/ServiceProviderDataTransformer.php
- src/Form/Type/ApiMediaType.php
- src/Form/Type/MediaType.php
- src/Model/Media.php
- src/Provider/BaseVideoProvider.php
- src/Provider/FileProvider.php
- tests/Controller/GalleryAdminControllerTest.php
- tests/Controller/MediaAdminControllerTest.php
- tests/Entity/GalleryManagerTest.php
- tests/Form/Type/AbstractTypeTest.php
- tests/Form/Type/MediaTypeTest.php
- tests/Provider/AbstractProviderTest.php
- tests/Provider/FileProviderTest.php
- tests/Security/RolesDownloadStrategyTest.php
- tests/Validator/FormatValidatorTest.php
> Manual merge

- tests/Command/FixMediaContextCommandTest.php
Maybe that was just a french developer being hungry? "manger" means "to
eat". Or maybe he was not hungry but angry, and needed anger management?
> Spell manager properly

- src/Resizer/SquareResizer.php
```markdown
- Added missing SquareResizer::$metadata property
```
> Added missing SquareResizer::$metadata property

- src/Controller/MediaController.php
- src/Extra/Pixlr.php
- src/Listener/BaseMediaEventSubscriber.php
- src/Templating/Helper/MediaHelper.php
I am targeting this branch, because it's BC.
```markdown
- Fixed phpdoc
```
> Fix phpdoc

- src/Resources/translations/SonataMediaBundle.bg.xliff
- src/Resources/translations/SonataMediaBundle.ca.xliff
- src/Resources/translations/SonataMediaBundle.en.xliff
- src/Resources/translations/SonataMediaBundle.fa.xliff
- src/Resources/translations/SonataMediaBundle.it.xliff
- src/Resources/translations/SonataMediaBundle.ja.xliff
- src/Resources/translations/SonataMediaBundle.pt_BR.xliff
- src/Resources/translations/SonataMediaBundle.ro.xliff
```markdown
- Added Catalan translations
```
Added catalan translations :)
> Add Catalan translations

- composer.json
```markdown
- Added support for latest imagine version
```
> Allow latest imagine version

- docs/reference/installation.rst
I am targeting this branch, because this is a typo fix.
> Fix typo in installation doc

- src/Resources/config/block.xml
- src/Resources/config/doctrine_mongodb_admin.xml
- src/Resources/config/doctrine_orm_admin.xml
- src/Resources/config/doctrine_phpcr_admin.xml
```markdown
- Make services public
```
> Make services public

- src/Command/AddMassMediaCommand.php
- tests/Command/CleanMediaCommandTest.php
- tests/Command/RemoveThumbsCommandTest.php
> Run new version of php-cs-fixer on the codebase

- src/Resources/config/provider.xml
- tests/DependencyInjection/SonataMediaExtensionTest.php
I am targeting this branch, because it's feature.
```markdown
- Added an alias for the pool
```
> Add an alias for the pool

- src/Command/AddMassMediaCommand.php
- tests/Admin/BaseMediaAdminTest.php
- tests/Admin/TestMediaAdmin.php
- tests/Block/Breadcrumb/BreadcrumbGalleryBlockService_Test.php
- tests/Block/Breadcrumb/BreadcrumbTest.php
- tests/Controller/Api/GalleryControllerTest.php
- tests/Controller/Api/GalleryTest.php
- tests/Controller/MediaAdminControllerTest.php
- tests/Entity/MediaTest.php
- tests/Fixtures/EntityWithGetId.php
> Cs fixer compliance

- composer.json
Closes #1509 
```markdown
- Allow KnpLabs/Gaufrette 0.8
```
> Allow KnpLabs/gaufrette 0.8

- src/Resources/config/provider.xml
```markdown
- Added alias for providers to use autoconfigure via DependencyInjection
```
> Alias for providers

- composer.json
- docs/reference/installation.rst
Doctrine has its own implementation since doctrine/dbal 2.6.0
> Remove references to json type

- src/Admin/GalleryAdmin.php
- src/Model/Gallery.php
- src/PHPCR/BaseGallery.php
I am targeting this branch, but I don't know if it's consider as a BC break.
Closes #1539 
```markdown
- Sort galleryHasMedias on GalleryAdmin::postUpdate
```
> Reorder galleryHasMedias on postUpdate

- docs/reference/installation.rst
Fix incorrect quote in installation documentation config.
> Fix incorrect quote

- docs/reference/usage.rst
> Fix formatting in usage documentation

- docs/reference/form.rst
- docs/reference/security.rst
Refs https://github.com/sonata-project/SonataAdminBundle/pull/5508
> small docs-fixes to be consistent

- src/Resources/translations/SonataMediaBundle.cs.xliff
> Add czech translations.

- src/Resources/views/Block/block_feature_media.html.twig
- src/Resources/views/Extra/pixlr_editor.html.twig
- src/Resources/views/Media/view.html.twig
- src/Resources/views/MediaAdmin/edit.html.twig
- src/Resources/views/MediaAdmin/list_image.html.twig
- src/Resources/views/Provider/thumbnail.html.twig
- src/Resources/views/Provider/view_youtube.html.twig
Fix some CS issues in Twig syntax.
> Fix some CS issues in Twig syntax

- tests/Generator/ODMGeneratorTest.php
Cass `Sonata\MediaBundle\Generator\ODMGenerator` was not covered by tests.
Closes https://github.com/sonata-project/SonataMediaBundle/issues/1342
> Test odm generator

- composer.json
- src/Provider/FileProvider.php
- src/Twig/Extension/MediaExtension.php
- src/Twig/Node/MediaNode.php
- src/Twig/Node/PathNode.php
- src/Twig/Node/ThumbnailNode.php
- src/Twig/TokenParser/MediaTokenParser.php
- src/Twig/TokenParser/PathTokenParser.php
- src/Twig/TokenParser/ThumbnailTokenParser.php
- tests/Provider/FileProviderTest.php
I labeled this as pedantic, should I add a changelog?
```markdown
- Use Mime Component to guess extension
```
> Remove Symfony deprecations

- UPGRADE-3.x.md
- src/Generator/DefaultGenerator.php
- src/Generator/IdGenerator.php
- src/Generator/ODMGenerator.php
- src/Generator/PHPCRGenerator.php
- src/Generator/PathGenerator.php
- src/Generator/UuidGenerator.php
- src/Resources/config/doctrine_mongodb.xml
- src/Resources/config/doctrine_orm.xml
- tests/Generator/IdGeneratorTest.php
- tests/Generator/ODMGeneratorTest.php
- tests/Generator/PathGeneratorTest.php
- tests/Generator/UuidGeneratorTest.php
- tests/Provider/BaseProviderTest.php
- tests/Provider/DailyMotionProviderTest.php
- tests/Provider/FileProviderTest.php
- tests/Provider/ImageProviderTest.php
- tests/Provider/PoolTest.php
- tests/Provider/VimeoProviderTest.php
- tests/Provider/YouTubeProviderTest.php
I think these names are more consistent with current implementations as they are not related to kind of persistence by to the type ID used by the model.
I am targeting this branch, it is supposed to be BC.
Reply to https://github.com/sonata-project/SonataMediaBundle/issues/1342#issuecomment-581243831
```markdown
- Renamed class `Sonata\MediaBundle\Command\DefaultGenerator` into `Sonata\MediaBundle\Command\IdGenerator`
- Renamed class `Sonata\MediaBundle\Command\ODMGenerator` into `Sonata\MediaBundle\Command\UuidGenerator`
- Renamed class `Sonata\MediaBundle\Command\PHPCRGenerator` into `Sonata\MediaBundle\Command\PathGenerator`
```
> Prepare generators rename

- composer.json
Allow "symfony/mime:^5.0", since the BC promise is not broken [between versions 4 and 5](https://github.com/symfony/mime/compare/v4.4.0..v5.0.0).
```markdown
- Added support for "symfony/mime:^5.0".
```
> Allow "symfony/mime:^5.0"

- tests/App/config.yml
- tests/Command/CleanMediaCommandTest.php
- tests/Command/FixMediaContextCommandTest.php
- tests/Command/RemoveThumbsCommandTest.php
- tests/Controller/GalleryAdminControllerTest.php
- tests/Controller/MediaAdminControllerTest.php
- tests/Controller/MediaControllerTest.php
- tests/Fixtures/FilesystemTestCase.php
- tests/Functional/Api/MediaControllerTest.php
- tests/Listener/ORM/MediaEventSubscriberTest.php
- tests/Metadata/ProxyMetadataBuilderTest.php
- Removed some deprecations
- Use Container instead of the mock to simplify
> Clean up tests

- docs/reference/usage.rst
This is another attempt to make the ~world~ docs better. Replaces https://github.com/sonata-project/SonataMediaBundle/pull/1723
> Document the type of `$mediaManager` in the code snippets

- docs/reference/media_context.rst
- src/Provider/ImageProvider.php
- src/Resources/config/validation.xml
- src/Resources/config/validators.xml
- src/Resources/translations/SonataMediaBundle.de.xliff
- src/Resources/translations/SonataMediaBundle.en.xliff
- src/Validator/Constraints/ImageUploadDimension.php
- src/Validator/Constraints/ImageUploadDimensionValidator.php
- tests/Fixtures/SonataClassificationBundle/Validator/Constraints/ImageUploadDimensionTest.php
- tests/Fixtures/SonataClassificationBundle/Validator/Constraints/ImageUploadDimensionValidatorTest.php
I am targeting this branch, because this feature respects BC.
Closes #1385
```markdown
- Add image size validation
```
> Add image size validation

- src/Controller/Api/GalleryController.php
- src/Controller/Api/MediaController.php
This PR revert type hints added in docblock which should not be added. They will be add corectly in other PR like https://github.com/sonata-project/SonataUserBundle/pull/1198.
I am targeting this branch, because it is FIX before release.
Changelog is not needed becouse this is fix for non release PR.
> Revert added type hints

- src/Model/Gallery.php
Use "spaceship" operator.
I am targeting this branch, because this change is pedantic and respects BC.
> Use "spaceship" operator

- src/Provider/DailyMotionProvider.php
- src/Provider/VimeoProvider.php
- src/Provider/YouTubeProvider.php
Small pedantic changes.
I am targeting this branch, because these changes are pedantic.
> Small pedantic changes

- src/Resources/config/doctrine/BaseGallery.mongodb.xml
- src/Resources/config/doctrine/BaseMedia.mongodb.xml
Edit Mongodb xml mapping and change "FieldName" attribute to "field-name"
I am targeting this branch, because want to push this correction to the next release.
Closes #1712
Update invalid mongodb xml mapping for BaseGallery.mongodb.xml and BaseMedia.mongodb.xml files
> Fix mongodb invalid xml mapping Error

- composer.json
```markdown
- support `sonata-project/datagrid-bundle:^3.0`
```
> add more version sonata-project/datagrid-bundle.

- src/Filesystem/Replicate.php
I am targeting this branch, because this is BC
Closes #1762
```markdown
- `Replicate::$master` and `Replicate::$slave`, in favor of `Replicate::$primary` and `Replicate::$secondary`
```
> changed words to primary and secondary 👍

- UPGRADE-3.x.md
- composer.json
- src/Security/ForbiddenDownloadStrategy.php
- src/Security/PublicDownloadStrategy.php
- src/Security/RolesDownloadStrategy.php
- src/Security/SessionDownloadStrategy.php
- tests/Security/ForbiddenDownloadStrategyTest.php
- tests/Security/PublicDownloadStrategyTest.php
- tests/Security/RolesDownloadStrategyTest.php
- tests/Security/SessionDownloadStrategyTest.php
I am targeting this branch, because this change respect BC.
```markdown
- Added support for `symfony/translation-contracts` ^1.1 || ^2.0
```
> Add translation contracts

- phpstan-baseline.neon
- phpstan.neon.dist
- psalm-baseline.xml
- psalm.xml
- src/DependencyInjection/SonataMediaExtension.php
- src/Resources/config/gaufrette.php
I am targeting this branch, because this is BC break.
> Improve SonataMedia Adapters

- UPGRADE-4.0.md
- src/Resources/config/doctrine_mongodb_admin.php
- src/Resources/config/doctrine_orm_admin.php
- src/Resources/config/provider.php
I am targeting this branch, because this is BC break.
```markdown
- All container parameters that were used to customize classes.
```
> Remove parameters from sonata admins

- src/Document/BaseGallery.php
- src/Document/BaseMedia.php
- src/Entity/BaseGallery.php
- src/Entity/BaseMedia.php
- src/Model/Gallery.php
- src/Model/GalleryInterface.php
- src/Model/GalleryItem.php
- src/Model/GalleryItemInterface.php
- src/Model/Media.php
- src/Model/MediaInterface.php
- src/Provider/VimeoProvider.php
- tests/App/Entity/Category.php
- tests/App/Entity/Context.php
- tests/App/Entity/Gallery.php
- tests/App/Entity/GalleryItem.php
- tests/App/Entity/Media.php
- tests/Block/GalleryBlockServiceTest.php
- tests/Controller/Api/GalleryControllerTest.php
- tests/Entity/MediaTest.php
I am targeting this branch, because this is a BC break.
Part of https://github.com/sonata-project/SonataMediaBundle/issues/1935
```markdown
- Added typehints to Entity classes
```
> Add typehints to Entities

- src/Resources/config/validation.xml
This removes a callback in validation.xml not removed in PR #1965 
I am targeting this branch, because the removed code was in master.
> Remove useless validation config

- src/Admin/BaseMediaAdmin.php
- src/Admin/GalleryAdmin.php
- src/Block/FeatureMediaBlockService.php
- src/CDN/CDNInterface.php
- src/CDN/CloudFrontVersion3.php
- src/CDN/Fallback.php
- src/CDN/PantherPortal.php
- src/CDN/Server.php
- src/Command/AddMassMediaCommand.php
- src/Command/CleanMediaCommand.php
- src/Command/RefreshMetadataCommand.php
- src/Command/RemoveThumbsCommand.php
- src/Command/SyncThumbsCommand.php
- src/Command/UpdateCdnStatusCommand.php
- src/Consumer/CreateThumbnailConsumer.php
- tests/CDN/PantherPortalTest.php
To admin, block, cdn, command and consumer directories
I am targeting this branch, because this is BC break.
Part of https://github.com/sonata-project/SonataMediaBundle/issues/1935
> Add typehints

- src/Controller/Api/GalleryController.php
- src/Controller/Api/MediaController.php
- src/Controller/MediaController.php
I am targeting this branch, because this is bc break
> Typehints to controllers

- src/Controller/GalleryAdminController.php
- src/Controller/MediaAdminController.php
I am targeting this branch, because this is where it fails.
```markdown
- Fixed controllers with SonataAdminBundle 4.
```
> Adapt controllers to be like the CRUDController on admin-bundle

- src/Controller/Api/MediaController.php
- src/Provider/BaseProvider.php
- src/Provider/BaseVideoProvider.php
- src/Provider/DailyMotionProvider.php
- src/Provider/FileProvider.php
- src/Provider/FileProviderInterface.php
- src/Provider/ImageProvider.php
- src/Provider/MediaProviderInterface.php
- src/Provider/Metadata.php
- src/Provider/MetadataInterface.php
- src/Provider/Pool.php
- src/Provider/VimeoProvider.php
- src/Provider/YouTubeProvider.php
- tests/App/Provider/TestProvider.php
- tests/Controller/Api/MediaControllerTest.php
I am targeting this branch, because this contains BC breaks.
Part of #1935
> Add typehints to provider folder

- phpstan-baseline.neon
- phpstan.neon.dist
- src/Command/RemoveThumbsCommand.php
- src/Command/SyncThumbsCommand.php
- src/Controller/MediaAdminController.php
- src/Filesystem/Replicate.php
- src/Model/Gallery.php
- src/Model/GalleryInterface.php
- src/Model/GalleryItemInterface.php
- src/Model/MediaInterface.php
- src/Provider/YouTubeProvider.php
- tests/Admin/GalleryItemAdminTest.php
- tests/Filesystem/ReplicateTest.php
- tests/Provider/FakeHttpWrapper.php
I am targeting this branch, because this is where it applies.
> Increase phpstan

- psalm.xml
- src/CDN/CloudFrontVersion3.php
- src/Generator/PathGenerator.php
- src/Model/NoDriverManager.php
- src/Provider/FileProvider.php
- src/Provider/Pool.php
- tests/App/Entity/Context.php
- tests/CDN/CloudFrontVersion3Test.php
I am targeting this branch, because psalm is level 6 here.
> Increase psalm to level 5

- src/Admin/GalleryAdmin.php
- src/Form/DataTransformer/ProviderDataTransformer.php
- src/Form/DataTransformer/ServiceProviderDataTransformer.php
- src/Form/Type/ApiMediaType.php
- src/Form/Type/MediaType.php
- src/Resources/config/api_form_doctrine_mongodb.php
- src/Resources/config/api_form_doctrine_orm.php
- src/Resources/config/form.php
- src/Resources/config/gaufrette.php
- src/Resources/translations/SonataMediaBundle.ca.xliff
- src/Resources/translations/SonataMediaBundle.de.xliff
- src/Resources/translations/SonataMediaBundle.en.xliff
- src/Resources/translations/SonataMediaBundle.es.xliff
- src/Resources/translations/SonataMediaBundle.fr.xliff
I am targeting this branch, because NEXT_MAJOR comments can be removed on master.
Continuation of #2018
> Fix more NEXT_MAJOR comments

- UPGRADE-3.x.md
- src/DependencyInjection/Compiler/ThumbnailCompilerPass.php
- src/Thumbnail/FormatThumbnail.php
- src/Thumbnail/ResizableThumbnailInterface.php
```markdown
- Added `ResizableThumbnailInterface`
```
> Add resizable thumbnail interface

- UPGRADE-3.x.md
- composer.json
- docs/reference/advanced_configuration.rst
- src/DependencyInjection/SonataMediaExtension.php
```markdown
- Deprecated integration with openStack / rackSpace
```
> Deprecate integration with openStack or rackSpace

- UPGRADE-3.x.md
- src/Filesystem/Replicate.php
Fix calls to undefined methods from Gaufrette.
These methods were replaced at knplabs/gaufrette 0.2.0. See KnpLabs/Gaufrette#98.
These issues were detected by PHPStan at #2035.
```markdown
- Method `Sonata\MediaBundle\Filesystem\Replicate::createStream()`;
- Implemented `Gaufrette\Adapter\StreamFactory` in `Sonata\MediaBundle\Filesystem\Replicate`.
- Missing implementation for `Gaufrette\Adapter\FileFactory` interface at `Sonata\MediaBundle\Filesystem\Replicate`;
- Call to undefined method `Adapter::createFileStream()`;
- Call to undefined method `Adapter::listDirectory()`.
- `Sonata\MediaBundle\Filesystem\Replicate::createFileStream()` in favor of `createStream()`.
```
> Fix calls to undefined methods from Gaufrette

- src/Block/FeatureMediaBlockService.php
- src/Block/GalleryListBlockService.php
Since Symfony 4 choices are provided as value.
```markdown
- Fix display of choices form types inside blocks.
```
> Flip choices options

- phpstan.neon.dist
- src/Admin/ORM/MediaAdmin.php
- tests/Block/GalleryListBlockServiceTest.php
Bump PHPStan level to 1.
I am targeting this branch, because these changes are pedantic and respect BC.
> Bump PHPStan level to 1

- src/DependencyInjection/Compiler/AddProviderCompilerPass.php
- src/DependencyInjection/Configuration.php
- src/Provider/BaseVideoProvider.php
- src/Provider/MediaProviderInterface.php
- src/Thumbnail/FormatThumbnail.php
- tests/Block/MediaBlockServiceTest.php
- tests/Controller/Api/MediaControllerTest.php
- tests/Controller/MediaControllerTest.php
- tests/DependencyInjection/Compiler/AddProviderCompilerPassTest.php
- tests/Provider/BaseProviderTest.php
- tests/Provider/DailyMotionProviderTest.php
- tests/Provider/FileProviderTest.php
- tests/Provider/ImageProviderTest.php
- tests/Provider/VimeoProviderTest.php
- tests/Provider/YouTubeProviderTest.php
- tests/Resizer/CropResizerTest.php
- tests/Resizer/SimpleResizerTest.php
- tests/Resizer/SquareResizerTest.php
- tests/Thumbnail/FormatThumbnailTest.php
- tests/Validator/FormatValidatorTest.php
I am targeting this branch, because this happens only on master.
> Fix admin format

- src/Resources/views/Block/block_feature_media.html.twig
- src/Resources/views/Block/block_gallery.html.twig
- src/Resources/views/Block/block_gallery_list.html.twig
- src/Resources/views/Block/block_media.html.twig
- src/Resources/views/Extra/pixlr_editor.html.twig
- src/Resources/views/Extra/pixlr_exit.html.twig
- src/Resources/views/Form/media_widgets.html.twig
- src/Resources/views/Gallery/view.html.twig
- src/Resources/views/GalleryAdmin/list.html.twig
- src/Resources/views/Media/view.html.twig
- src/Resources/views/MediaAdmin/edit.html.twig
- src/Resources/views/MediaAdmin/inner_row_media.html.twig
- src/Resources/views/MediaAdmin/list.html.twig
- src/Resources/views/MediaAdmin/list_image.html.twig
- src/Resources/views/MediaAdmin/list_outer_rows_mosaic.html.twig
- src/Resources/views/MediaAdmin/select_provider.html.twig
- src/Resources/views/Provider/thumbnail.html.twig
- src/Resources/views/Provider/view_image.html.twig
- src/Resources/views/Provider/view_vimeo.html.twig
I am targeting this branch, because this is mostly pedantic.
> Improve consistency on twig views

- src/Command/AddMassMediaCommand.php
- src/Command/AddMediaCommand.php
- src/Command/CleanMediaCommand.php
- src/Command/FixMediaContextCommand.php
- src/Command/MigrateToJsonTypeCommand.php
- src/Command/RefreshMetadataCommand.php
- src/Command/RemoveThumbsCommand.php
- src/Command/SyncThumbsCommand.php
- src/Command/UpdateCdnStatusCommand.php
- src/DependencyInjection/Compiler/AddProviderCompilerPass.php
- src/DependencyInjection/Compiler/GlobalVariablesCompilerPass.php
- src/DependencyInjection/Compiler/ThumbnailCompilerPass.php
- src/DependencyInjection/Compiler/TwigStringExtensionCompilerPass.php
- src/Twig/Extension/FormatterMediaExtension.php
- src/Twig/Extension/MediaExtension.php
- src/Twig/GlobalVariables.php
- src/Twig/Node/MediaNode.php
- src/Twig/Node/PathNode.php
- src/Twig/Node/ThumbnailNode.php
- src/Twig/TokenParser/MediaTokenParser.php
- src/Twig/TokenParser/PathTokenParser.php
- src/Twig/TokenParser/ThumbnailTokenParser.php
- tests/Twig/Extension/MediaExtensionTest.php
I am targeting this branch, because this could be considered as BC break.
Closes #2108 
```markdown
- Added internal on Commands, Compiler Passes and Twig extensions 
```
> Mark internal classes and construct

- docs/reference/installation.rst
- src/Resources/config/routing/gallery.xml
- src/Resources/config/routing/media.xml
I am targeting this branch, because this should be done on my last PR #2110 .
Also part of #2106
> Remove deprecated routes and fix documentation to reflect recent changes.

- src/Security/RolesDownloadStrategy.php
- tests/Security/RolesDownloadStrategyTest.php
Closes #2116 
```markdown
- Fixed deprecation when downloading media through `downloadAction()`
```
> Check for each role separately on downloadAction
